### ISSUE TITLE
wow `> 120` stars, thank you everyone 🙏

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#112]
we've been busy making dotenvx better:

* Added `get` command: (`dotenvx get KEY`)
* Added `scan` command: (`dotenvx scan`)
* Added `--env` flag: (`dotenvx run --env="HELLO=World" -- yourcommand`)
* Added `.env.vault` monorepo support: (`dotenvx encrypt path/to/directory`)
* Added `ls` command: (`dotenvx ls`)
* Windows support and improvements

**Comment by zane-commeatio** [comment]
So dotenvx replaces dotenv-vault ?

**Comment by motdotla** [comment]
@zane-commeatio, yes, I think in time it will. it has a few advantages:

* extra tooling around `.env` files
* use with `.env.vault` without requiring a 3rd party service
* opt-in to hosting/backing up of your `.env.keys`

dotenv-vault on the other hand doesn't have the additional tooling around .env files, requires the 3rd party cloud service to generate the .env.vault files, and you have to use the hosting service to get its benefits.

that said, dotenvx doesn't have team features yet, but those are coming as soon as we can get to them.
