### ISSUE TITLE
PM2 support

### ISSUE THREAD

**Issue by pjaydev** [dotenvx/dotenvx#124]
Hi,

are there any plans to allow the use of `dotenvx` when running a Node.js app in an [PM2](https://pm2.keymetrics.io/) environment?

Currently I do not see any way, since pm2 manages its own way of injecting env variables and does not offer a config option to embed the `node` call in an external command. Or am I overlooking something?

Thanks for your work!

**Comment by motdotla** [comment]
can you just wrap the pm2 command with `dotenvx run`?

`dotenvx run -- yourpm2 command`

**Comment by pjaydev** [comment]
No, this won't work since pm2 creates new environments for all of its Node processes.

The main reason why I switched from **dotenv** to **dotenvx** was the support for multiple `.env` files.  

I just realized that I am still able to use dotenvx also with pm2 processes by importing it the "old-fashioned" way right on top of my `start.js` script, above any of my other `import` instructions:

```javascript
import {config as dotenvConfig} from '@dotenvx/dotenvx';
dotenvConfig({
    path: [
        ".env",
        ".env.default",
    ]
});
...
```

This works for my case so far. But of course, it is not a solution in situations, where you do not have the option to modify the codebase.

**Comment by motdotla** [comment]
@pjaydev i created a pm2 guide here: https://dotenvx.com/docs/process-managers/pm2

does that solve your problem and wish?

**Comment by ChinKX** [comment]
I managed to solve my issue by using the dotenvx directly in the script field of the `ecosystem.config.js` file.

```js
module.exports = {
  apps : [{
    name: 'app',
    script: 'dotenvx run --env-file=.env.production -- node ./app.js',
  }]
};
```

I am not entirely sure what's happening but my guess is similar to what @pjaydev mentioned which is pm2 created an separate environment/process which does not include the env variables from the .env file. Any explanations are welcome and appreciated. Thanks in advance!

**Comment by motdotla** [comment]
> I managed to solve my issue by using the dotenvx directly in the script field of the `ecosystem.config.js` file.
> 
> 
> 
> ```js
> 
> module.exports = {
> 
>   apps : [{
> 
>     name: 'app',
> 
>     script: 'dotenvx run --env-file=.env.production -- node ./app.js',
> 
>   }]
> 
> };
> 
> ```
> 
> 
> 
> I am not entirely sure what's happening but my guess is similar to what @pjaydev mentioned which is pm2 created an separate environment/process which does not include the env variables from the `.env.production` file. Any explanations are welcome and appreciated. Thanks in advance!

yes this is what we recommend in https://dotenvx.com/docs/process-managers/pm2

i don't remember the reason but something about how pm2 forks processes vaguely.
