### ISSUE TITLE
--env-file flag collision for node 20

### ISSUE THREAD

**Issue by keoz-simon** [dotenvx/dotenvx#131]
Hey! I'm trying to implement dotenvx to my TypeScript project.

This is my desired command:
```dotenvx run --env-file=.env --env-file=.env.test --env-file=.env.test.local --overload ...```

In case `.env.test.local` or any other --env-file option is not present, dotenvx fails. I think native fs error bubbles up. I'd suggest and need for my case an option, that it doesn't fail if a file is not present. I think it's not mandatory to let it fail. What do you think?

thanks!

**Comment by motdotla** [comment]
i think you're right. it shouldn't fail. it should just warn. will patch up.

**Comment by motdotla** [comment]
what version are you on? looks like this behavior is already correct - warns on missing file:

<img width="1386" alt="Screenshot 2024-03-19 at 10 42 44 AM" src="https://github.com/dotenvx/dotenvx/assets/3848/2174036b-80ce-4d39-ac9b-d99dd49bb77c">

**Comment by simonhard** [comment]
<img width="1043" alt="CleanShot 2024-03-19 at 18 49 52@2x" src="https://github.com/dotenvx/dotenvx/assets/1381808/072eb71d-024b-4454-a579-4cea5f7b0507">
hm.. should be the same. It doesn't even logs any debug log but exits early with exit 9 sigkill.

**Comment by motdotla** [comment]
what node version are you using here? maybe there is a flag collision i need to look into.

**Comment by simonhard** [comment]
@motdotla v20.11.1
Which one are you using? I could recheck with yours.
OS is macOS 14.3

**Comment by simonhard** [comment]
yes, that's the issue. node@18 works. node@20 doesn't.

**Comment by motdotla** [comment]
we used --env-file because we like the principle of least surprise (keep in mind many devs use the binary rather than the npm install (in which case this is not an issue))

that said, to unblock you, use -f as the flag instead of --env-file. that should work. 

i'll also reconsider the flag name.

**Comment by simonhard** [comment]
If I didn't get you wrong: binary doesn't work too. But I'm totally with you using this flag name.
 
`-f` would be a good workaround. Maybe + warning in README.
nevertheless best solution would be no collision at all.
thanks for your work

**Comment by motdotla** [comment]
binary should work, but not the `node_modules/.bin/dotenvx` since it's still dependent on the running node version.

the binary (or brew) installs can be done via:

```
brew install dotenvx/brew/dotenvx
or 
curl -fsS https://dotenvx.sh/ | sh
```

**Comment by motdotla** [comment]
there is some chatter with the Node team that they will replace the error with a warning - which I hope and expect to see.

So until then, I'm adding this issue to a new FAQ:

https://github.com/dotenvx/dotenvx?tab=readme-ov-file#faq
