### ISSUE TITLE
Traverse up to find .env file automatically

### ISSUE THREAD

**Issue by pkuczynski** [dotenvx/dotenvx#133]
I am working on a monorepo setup, where I have following structure of packages

```
src/
  services/
    service-1/
    service-2/
.env
```

I would like both services to share same `.env`, so in `srevice-1/package.json` I have a script:

```
"start:dev": "dotenvx run --env-file=${PWD}/../../../.env -- pnpm ts-node-dev -- src/index.ts",
```

Unfortunately when I run it from inside service-1 directory, I am getting an error:

```
node: /Users/piotr/Projects/work/x/y/src/services/service-1/../../../.env: not found
```

which I don't understand, as this file is definitely there when I run `ls`. Any idea why it's not being picked up?

Would it be possible for `dotenvx` to traverse folders up, until `.env` file is found, so I do not have to manually specify `--enf-file`? Similar thread here: https://github.com/motdotla/dotenv/issues/238#issuecomment-348017037

**Comment by motdotla** [comment]
dotenvx should do so. it's completely flexible with filepaths. 

try changing `--env-file` flag to just `-f`. the error you are receiving is actually from latest node's `--env-file` flag (we chose to use the same flag name, but their implementation currently has some edge case bugs we are seeing crop up).

that will give you a better idea of what is going on.

 then run `cat /Users/piotr/Projects/work/x/y/src/services/service-1/../../../.env` to triple check that can render.
