### ISSUE TITLE
Postgres Official Image fails to launch with `dotenvx run -- postgres`

### ISSUE THREAD

**Issue by frostbytedata** [dotenvx/dotenvx#142]
I have a simple Dockerfile using an official Postgres image that does not seem to want to run Postgres through `dotenvx run`. This is a minimal Docker file that fails to run with the following error:

### Error

```bash
[dotenvx@0.27.1] injecting env (21) from encrypted .env.vault
 postgres: could not access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
 Command failed with exit code 2: /usr/local/bin/postgres
 command [postgres] failed
 
   try without dotenvx: [postgres]
 
 if that succeeds, then dotenvx is the culprit. report issue:
<https://github.com/dotenvx/dotenvx/issues/new>
```

### Dockerfile

```Dockerfile
# Use the official PostgreSQL Alpine image
FROM postgres:13-alpine

# Copy the dotenv vault file over to the container
COPY --chown=postgres:postgres .env.vault .

# Install cURL
RUN apk add --no-cache curl
# Install dotenvx
RUN curl -fsS https://dotenvx.sh/ | sh

# Expose the PostgreSQL port
EXPOSE 5432

# Allow remote connections to PostgreSQL from all IP addresses with md5 authentication
RUN echo "host all  all    0.0.0.0/0  md5" >> /var/lib/postgresql/data/pg_hba.conf

USER postgres

ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# hijack the launch of the postgres service to ensure the .env.vault file is decrypted and loaded.
# Remember, you must ensure the DOTENV_KEY environment variable is available to this
# dockerfile at build time. This is the key used to decrypt the .env.vault file.
CMD ["dotenvx", "run", "--", "postgres"]
```

I have inspected the container and confirmed that `dotenvx` is installed and available, and that the `/var/lib/postgresql/data/postgresql.conf` file is indeed present. Why might it be causing Postgres to not find its own configuration file in the default directory? I have tried many variations including passing the config location in manually like this: 

`CMD ["dotenvx", "run", "--", "postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]`.

I am happy to provide additional info. Thank you.

**Comment by frostbytedata** [comment]
> if you remove the dotenvx run portion in your CMD, does postgres start up successfully?
> 
> CMD postgres
> 
> (at first glance, it looks like it could be a file permissions issue allowing postgres to access/read that file)

Yep it runs and starts fine without the `dotenvx` prefix. I should have specified that in my original post. I briefly looked into the `execa` docs to try and see if there was something happening there that would be causing this, but it is a bit out of my experience zone.

**Comment by motdotla** [comment]
ok, i'll work on duplicating the issue

**Comment by motdotla** [comment]
i'm receiving the same error you are getting without using dotenvx.

example code: https://github.com/motdotla/pgtest

![pgerror](https://github.com/dotenvx/dotenvx/assets/3848/73ee0de7-9073-4dd9-b063-5f16326f7cc2)


are you sure your `/var/lib/postgresql/data/postgresql.conf` exists on your machine? I don't believe this would be from the container - since you are using a RUN command (which looks for your local machine's filepath)

**Comment by motdotla** [comment]
if you run `cat /var/lib/postgresql/data/postgresql.conf` on your local machine, do you see the file?

**Comment by frostbytedata** [comment]
> if you run `cat /var/lib/postgresql/data/postgresql.conf` on your local machine, do you see the file?

Thanks for digging into this with me. I am running this within my Docker container, so that file wouldn't exist on my local machine. Do you have a way to run my Dockerfile? That is interesting you are also getting that error when you try it on your local machine. I am now wondering if the base image `postgres:13-alpine` is potentially doing something I don't know about.

**Comment by frostbytedata** [comment]
Well I eventually got this working after many many hours of frustration. I'm going to close this as I don't have any evidence that it's an issue with `dotenvx`. But I will leave my solution here for anyone else stumbling onto this issue in the future.

### My Solution

I eventually ended up creating a custom `ENTRYPOINT` file based on the information in this thread: https://github.com/docker-library/postgres/pull/496
For some reason, this seems to work for me when other techniques did not. Here is my `pg-custom-entrypoint.sh` file:

#### pg-custom-entrypoint.sh
```sh
#!/usr/bin/env bash
set -Eeo pipefail

# Example using the functions of the postgres entrypoint to customize startup to always run files in /always-initdb.d/

source "$(which docker-entrypoint.sh)"

docker_setup_env
docker_create_db_directories
# assumption: we are already running as the owner of PGDATA

# This is needed if the container is started as `root`
#if [ "$1" = 'postgres' ] && [ "$(id -u)" = '0' ]; then
#	exec gosu postgres "$BASH_SOURCE" "$@"
#fi

if [ -z "$DATABASE_ALREADY_EXISTS" ]; then
	docker_verify_minimum_env
	docker_init_database_dir
	pg_setup_hba_conf

	# only required for '--auth[-local]=md5' on POSTGRES_INITDB_ARGS
	export PGPASSWORD="${PGPASSWORD:-$POSTGRES_PASSWORD}"

	docker_temp_server_start "$@" -c max_locks_per_transaction=256
	docker_setup_db
	docker_process_init_files /docker-entrypoint-initdb.d/*
	docker_temp_server_stop
else
	docker_temp_server_start "$@"
	docker_process_init_files /always-initdb.d/*
	docker_temp_server_stop
fi

exec postgres "$@"
```

And here is my resulting Dockerfile:
#### Dockerfile
```Dockerfile

# Use the official PostgreSQL Alpine image
FROM postgres:13-alpine

# Copy the dotenv vault file over to the container
COPY --chown=postgres:postgres .env.vault .
COPY --chown=postgres:postgres pg-custom-entrypoint.sh /usr/local/bin/pg-custom-entrypoint.sh

# Install cURL
RUN apk add --no-cache curl
# Install dotenvx
RUN curl -fsS https://dotenvx.sh/ | sh

# Expose the PostgreSQL port
EXPOSE 5432

# Allow remote connections to PostgreSQL from all IP addresses with md5 authentication
RUN #echo "host all  all    0.0.0.0/0  md5" >> /var/lib/postgresql/data/pg_hba.conf

USER postgres

# hijack the launch of the postgres service to ensure the .env.vault file is decrypted and loaded.
# Remember, you must ensure the DOTENV_KEY environment variable is available to this
# dockerfile at build time. This is the key used to decrypt the .env.vault file.
CMD ["dotenvx", "run", "--", "pg-custom-entrypoint.sh"]
```

Thanks for taking the time to try and reproduce this issue. Hope this comment can help others in the future. 👋

**Comment by motdotla** [comment]
ok, glad you were able to solve the issue @frostbytedata. thanks for sharing for others!

**Comment by nullbio** [comment]
Figured out how to do this without creating a custom entrypoint script @frostbytedata. 

Use the following as your `command:` in your compose.yml file (instead of defining it in the image):

`command: sh -c "dotenvx run -- /usr/local/bin/docker-entrypoint.sh postgres"`

I'll share what else I've learned shortly here: https://github.com/dotenvx/dotenvx/issues/235, once I finish the setup.
