### ISSUE TITLE
`hub push` not working on Windows

### ISSUE THREAD

**Issue by SuperchupuDev** [dotenvx/dotenvx#164]
The following files use `dev/null` for suppressing error messages on git, which doesn't work on Windows:
![image](https://github.com/dotenvx/dotenvx/assets/53496941/a921cf81-e0c0-4c33-a0ec-3b13a85d2f06)

This makes dotenvx throw the following error:
![image](https://github.com/dotenvx/dotenvx/assets/53496941/299972ba-6e7a-408c-803d-607334b6cd31)

**Comment by motdotla** [comment]
are you using powershell here?

this is not using the dotenvx.exe, correct?

**Comment by SuperchupuDev** [comment]
yep, using powershell 7, and not from the exe

**Comment by motdotla** [comment]
looks like the only way to to do this is to start adding OS checks throughout. so i'll get a start on that.

**Comment by motdotla** [comment]
actually, `execa` might solve this problem for us - rather than using `child_process`

**Comment by motdotla** [comment]
most of this is patched now using execa. a little more work to do.

**Comment by motdotla** [comment]
this is fixed with `v0.30.2`
