### ISSUE TITLE
Having issues with env variable expansion 

### ISSUE THREAD

**Issue by arvindsivakumar** [dotenvx/dotenvx#165]
## Background 
I wanted to get some clarity on the best way to pass env vars defined in a `.env.xxx` file to a shell command.

I'm most interested in using this with Docker build arguments to avoid having to redefine env vars within Github Actions. This way the only secret that will need to be defined is the `.env.keys` and everything else can be parsed from the appropriate context at runtime from `.env.vault`. 

## Reproduction

**.env.example**
```dotenv filename=".env.example"
HELLO="WORLD"
```
**Dockerfile**
```dockerfile filename="Dockerfile"
FROM alpine:3.14

ARG $HELLO
ENV HELLO $HELLO

ENTRYPOINT ["/bin/sh" , "-c", "echo ${HELLO}"]
```

If for example I wanted to run the following, I would get an empty output: 

``` bash  filename="failure.sh"
dotenvx encrypt

dotenvx run --env-file=.env.example -- docker build --build-arg HELLO=$HELLO. -t hello_env

docker run hello_env
``` 

While the following will work: 

``` bash  filename="success.sh"
docker build --build-arg HELLO="hello". -t hello_env

docker run hello_env
```

**Comment by motdotla** [comment]
the bash example helps with this one. it needs to call out to a subshell:

```
dotenvx run --quiet -- sh -c 'docker build --build-arg HELLO=$HELLO . -t hello_env'
docker run hello_env
```

alternatively you can call directly to the `dotenvx get` command from the `--build-arg`:

```
docker build --build-arg HELLO="$(dotenvx get HELLO)" . -t hello_env
docker run hello_env
```

(also a side note, looks like your Dockerfile should remove the `$` dollar sign from the `ARG` line)

```
FROM alpine:3.14

ARG HELLO
ENV HELLO $HELLO

ENTRYPOINT ["/bin/sh" , "-c", "echo Hello ${HELLO}"]
```

**Comment by motdotla** [comment]
keep in mind, this approach is encoding secrets into your built container - which means if your container ever leaks someone could gain access to the secrets.

For an approach that instead adds the `.env.vault` file and passes the `DOTENV_KEY` at runtime of the container you can follow this Docker guide here: https://dotenvx.com/docs/platforms/docker

**Comment by arvindsivakumar** [comment]
> alternatively you can call directly to the dotenvx get command from the --build-arg:

Oh sweet, didn't know about `dotenvx get` that gets me 99% of the way there. 

Looks like there's some log output that is getting emitted by default, so had to modify that script slightly to `dotenvx get HELLO | sed -n '2 p'` to get rid of the `[dotenv@16.4.5][INFO] Loading env from encrypted .env.vault` output. 

But otherwise this works like a charm, appreciate the quick response. 

> keep in mind, the approach above is encoding secrets into your built container - which means if your container ever leaks someone could gain access to the secrets.

Right definitely hear that point, think the use case I was trying solve for was more around different contexts where `.env` files could be used to manage config. These values are not necessarily "secret" but standardizing on `dotenvx` as the means of accessing config across concerns like development, CI, and application runtime and just swap based on the `DOTENV_KEY` is pretty ergonomic.

**Comment by motdotla** [comment]
> looks like there's some log output that is getting emitted by default

that was a bug we recently patched. if you update to the latest version `v0.30.0` that shouldn't be an issue any longer.

> These values are not necessarily "secret" but standardizing on dotenvx as the means of accessing config across concerns like development, CI, and application runtime and just swap based on the DOTENV_KEY is pretty ergonomic.

Great!
