### ISSUE TITLE
`get` command does not fail when key is not found

### ISSUE THREAD

**Issue by skycaptain** [dotenvx/dotenvx#184]
The `get` command returns `undefined` and exits with `0`when a key is not found:

```plain
$ dotenvx get BAZ --env FOO=BAR
undefined
$ echo $?
0
```

Instead, I would expect the command to fail and return with a non-zero exit code.

**Comment by motdotla** [comment]
i think you're right. i'll think on this a bit more, but likely adjust to exit 1.

**Comment by motdotla** [comment]
released as `v0.35.1` https://github.com/dotenvx/dotenvx/blob/main/CHANGELOG.md#0351
