### ISSUE TITLE
Add watch  mode for dev use

### ISSUE THREAD

**Issue by ayothealoko** [dotenvx/dotenvx#190]
I just started using this package and I love it! However I would like watch my .env files so that I don't have to manually reset my server while developing.

I want to create a pull request that does the following and would like some feedback:

Introduce a new flag "-w"

`dontenvx run -w -f .env.local -- npm run dev
`

With this "-w" flag set, all env files provided will be watched and will reset the environment accordingly. This will be a total reset to preserve cascading of variables in various env files. In addition, the command after "--" , for example  "-- npm run dev",  will rerun so as to reset any environment variables  that have already been loaded.

**Comment by motdotla** [comment]
> I just started using this package and I love it!

💛

> With this "-w" flag set, all env files provided will be watched

Interesting, this would be a useful feature, but my first thought is - does `nodemon` do this well already?

**Comment by ayothealoko** [comment]
So I  just tried it

`
nodemon --watch .env.local --exec  'dontenvx run  -f .env.local -- npm run dev '
`
It  a bit verbose but it gets the job done. At the end of the day, it will all get shoved into the npm script anyways. 
So I think it makes sense to just use it this way.
Thanks for the help.
