### ISSUE TITLE
A question of using for nextjs - subshell expansion

### ISSUE THREAD

**Issue by ccforeverd** [dotenvx/dotenvx#199]
Hi~ I have a question in using .env with nextjs.

Mine is a monorepo based pnpm:

- apps
  - next-web
    - package.json
- package.json
- .env

``` bash
# .env (root)
BF_PORT_NEXT_DEV=8200
```

``` jsonc
// apps/next-web/package.json
{
  "scripts": {
    "dev": "next dev -p $BF_PORT_NEXT_DEV",
    "dev:bad: "dotenvx run -f ../../.env -- next dev -p $BF_PORT_NEXT_DEV"
  }
} 
```

``` jsonc
// package.json
{
  "scripts": {
    "dev:next": "dotenvx run --quiet -- pnpm -F \"./apps/next-web\" dev",
    "dev:next:bad": "pnpm -F \"./apps/next-web\" dev:bad"
  }
}
```

When run `pnpm dev:next`, it's ok.

But run `pnpm dev:next:bad`, throw:

``` bash
[dotenvx@0.37.1] injecting env (4) from ../../.env
error: option '-p, --port <port>' argument missing
```

(First line by dotenvx, second line by nextjs)

I got confused so to make this issue, maybe it helps to make a monorepo example :D

Thanks

**Comment by ccforeverd** [comment]
In other apps, i use config file:

- apps
  - react-a
    - vite.config.ts
  - react-b
    - rsbuild.config.ts

``` ts
// apps/react-a/vite.config.ts
export default defineConfig(({ mode }) => {
  const env: Record<string, string> = {
    ...loadEnv(mode, '.'),
    ...loadEnv(mode, '../..', 'BF'),
  }
  
  // ...
}

// apps/react-b/rsbuild.config.ts
export default defineConfig(({ env, envMode, command }) => {
  logger.info('env:', env)
  logger.info('envMode:', envMode)
  logger.info('command:', command)

  logger.log()

  const { parsed: innerAppEnvs } = loadEnv({ mode: envMode, prefixes: ['BF_'] })
  const { parsed: rootEnvs } = loadEnv({
    mode: envMode,
    prefixes: ['BF_'],
    cwd: path.resolve(process.cwd(), '../../'),
  })

  const envs = {
    ...rootEnvs,
    ...innerAppEnvs,
  }

  // ...
}
```

Only for nextjs, the `port` config must in command line.

**Comment by motdotla** [comment]
hi @ccforeverd, thank you for using @dotenvx. I don't understand what your question is though? Seems like you resolved things with pnpm?

**Comment by ccforeverd** [comment]
> hi @ccforeverd, thank you for using @dotenvx. I don't understand what your question is though? Seems like you resolved things with pnpm?

Sorry, I mean that if i start my nextjs app in path "(project)/apps/next-web" with script "dev:bad" in "(project)/apps/next-web/package.json", it will throw error "injecting env (4) from ../../.env" because i load ".env" from the root path of project by using "dotenvx run -f ../../.env -- next dev -p $BF_PORT_NEXT_DEV".

I can't resolve this error but avoid it by start nextjs app in path "(project)/" with script "dev" in "(project)/package.json" which is "dotenvx run --quiet -- pnpm -F \"./apps/next-web\" dev" and it run well.

The different is `"../../.env"` and `start cwd`, so i guess there maybe some protection of path which is not allow to use parent path by dotenvx.

Like https://github.com/dotenvx/dotenvx/issues/199#issuecomment-2097405062, in other apps i resolve root .env in their own dir but resolve next app in the root dir, it's a little bit Disharmonious.

Anyway, all runs well now, thanks.

**Comment by motdotla** [comment]
ah, i see @ccforeverd. hmm, that should work though. i know it is extra work, but would you mind creating an example repo and publishing it somewhere to github? I can pull it down to duplicate the issue and then debug.

**Comment by ccforeverd** [comment]
> ah, i see @ccforeverd. hmm, that should work though. i know it is extra work, but would you mind creating an example repo and publishing it somewhere to github? I can pull it down to duplicate the issue and then debug.

OK, please wait a moment.

**Comment by ccforeverd** [comment]
https://github.com/ccforeverd/monorepo-nextjs

<img width="779" alt="image" src="https://github.com/dotenvx/dotenvx/assets/7246675/0b647ca7-9cf7-4ff2-b374-70ea2d8bb296">

<img width="1178" alt="image" src="https://github.com/dotenvx/dotenvx/assets/7246675/7db79ef6-7638-4423-ab93-26b5decb715a">

- `pnpm i`
- `pnpm dev:next`
- `pnpm dev:next:bad`

**Comment by motdotla** [comment]
thank you. that was very helpful. the issue is that the shell is expanding `$BF_PORT_NEXT_DEV` before `dotenvx` has a chance to inject it - because of how shell expansion works. the quick fix is to do this:

```json
// apps/next-web/package.json
"dev:bad": "dotenvx run -f ../../.env -- sh -c 'next dev -p $BF_PORT_NEXT_DEV'",
```

running your command in a subshell like this will delay that shall expansion.

that said, maybe we should support being able to just wrap the entire command in quotes. 

```
"dev:bad": "dotenvx run -f ../../.env -- 'next dev -p $BF_PORT_NEXT_DEV'",
```

i'll think on that.

**Comment by ccforeverd** [comment]
Very much thanks it works!

**Comment by motdotla** [comment]
this is documented here now for posterity: https://dotenvx.com/docs/advanced/run-shell-expansion

**Comment by ccforeverd** [comment]
> this is documented here now for posterity: https://dotenvx.com/docs/advanced/run-shell-expansion

Very nice job!
