### ISSUE TITLE
add dotenvx encrypt path option

### ISSUE THREAD

**Issue by xavierbeillas** [dotenvx/dotenvx#203]
I wish I could specify a path option for the encrypt subcommand.
I'm use to locate all my env files in `src/envs/` then I would run the encrypt command this kind of way :
`dotenvx encrypt envs`

**Comment by motdotla** [comment]
you can today. that's built-in.

```
$ dotenvx encrypt src/envs
```

---

note: as of literally just 2 minutes ago :) we are sunsetting `.env.vault` files. tooling for them will move to `dotenvx vault [COMMAND]`. the new encryption format is inlined and using asymmetric cryptography. 

you can read more [here](https://github.com/dotenvx/dotenvx?tab=readme-ov-file#encryption) and [here](https://github.com/dotenvx/dotenvx?tab=readme-ov-file#what-happened-to-the-envvault-file)

<img width="875" alt="Screenshot 2024-05-09 at 10 25 11 AM" src="https://github.com/dotenvx/dotenvx/assets/3848/878dbb5e-2016-44db-82de-f7e5005b9975">

**Comment by xavierbeillas** [comment]
Wow just found it 30 seconds ago and did not get too fast to delete my issue ! Thanks for your fast reply !
Is there a way to get back the dotenv file from the .env.vault and .env.keys ?

**Comment by motdotla** [comment]
yes, you can run the command `dotenvx decrypt path/to/directory`. that will combine your .env.keys with your .env.vault file to decrypt your `.env*` files

**Comment by xavierbeillas** [comment]
Found this package 30 minutes ago and wow this package just blow my mind ! I guess you just solved a 15 years problem haha ! Thank you so much ! 🔥
