### ISSUE TITLE
when specifying -f .env.production and `DOTENV_PRIVATE_KEY_PRODUCTION` cannot be found, then warn the user

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#210]
this would have been helpful when deploying to Railway. There were multiple gotchas with their service around including encrypted .env files.

**Comment by happyjamstack** [comment]
For the record. Railway seems to work when reading `.env` files with the new `0.43.0`. I'm including the `DOTENV_PRIVATE_KEY_PRODUCTION` variable, an encrypted .env file, and getting the vars like:

```node
const dotenv = require('@dotenvx/dotenvx')
dotenv.config({path:'.env'})
console.log(process.env.VAR_1)
// =decrypted_value1
```

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/349

will be released as a patch shortly.

<img width="1115" alt="image" src="https://github.com/user-attachments/assets/d9119f08-f866-403d-b1c1-20555774031c">
