### ISSUE TITLE
when running `dotenvx convert` write original `.env*` file to `.env*.previous`

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#221]
this way if there is an edge case bug with `encryptme` (we haven't tested all edge cases yet), the user does not lose their important .env data.

**Comment by motdotla** [comment]
i think should be unnecessary if we get all edge cases covered. it adds so much noise.

**Comment by bingtsingw** [comment]
Maybe we can make `convert` command more general to convert to or from encrypted data:
`dotenvx convert --encrypt -f .env.xxx -o .env.xxx.encrypted`
`dotenvx convert --decrypt -f .env.xxx.encrypted -o .env.xxx`

`--encrypt` and `-o` can be designed as optional to be compatible with current command

**Comment by motdotla** [comment]
@bingtsingw the `convert` command is now the `encrypt` command and you can now use `--stdout` flag for composbility:

```
$ dotenvx encrypt -f .env.xxx --stdout > .env.xxx.encrypted
```

you can do the same with decrypt:

```
$ dotenvx decrypt -f .env.xxx.encrypted > .env.xxx.decrypted
```

this adds a lot of flexibility and i think nullifies the need for a noise `.env.previous` at this time. closing this out.
