### ISSUE TITLE
Encrypting works fine. What about decrypting?

### ISSUE THREAD

**Issue by happyjamstack** [dotenvx/dotenvx#223]
I cannot find how to decrypt .env programattically using node. I would expect to find something like this in the documentation for someone using node to load secrets. But I cannot find this.

```node
const dotenv = require('@dotenvx/dotenvx')
let opts = { path: '.env.production', keys: '.env.keys' }
// or
opts = { path: '.env.production', keys: process.env.key })

console.log(`Hello ${process.env.HELLO}`)
```
There is no way to do it from Node itself right?
[this is how it is meant to be done?](https://dotenvx.com/docs/advanced/run-dotenv-private-key-production) The method above is not supported for decryption?

**Comment by motdotla** [comment]
let me put together a guide on using it inside node with the require. i haven't yet. give me some time. all the best.

**Comment by motdotla** [comment]
while you're waiting, how did you find `dotenvx` ?

**Comment by motdotla** [comment]
ok, actually this is approach is currently not supported. my mistake. patching up.

**Comment by motdotla** [comment]
progress is happening here: https://github.com/dotenvx/dotenvx/pull/225

**Comment by happyjamstack** [comment]
That was unbelievably fast. Never have i seen someone respond fix and commit so quickly!

I found `dotenvx`  while looking at `dotenv` and seeing this package recommended by you. I wanted to use the latest recommended practice for a new project and thought I might need encryption. At the moment I am using Railway and I could just copy paste secrets into their frontend which is supposed to inject them, however, for some reason Railway doesnt seem to be recognizing all my variables unless i include the `.env` in source control, so I decided to try leaving them in the source but encrypting.

**Comment by happyjamstack** [comment]
In case anyone else reads this. To load encyrpted .env in node now, you just need 

File: [./test.js]
```node
const dotenv = require('@dotenvx/dotenvx').config({path: ".env.whatever" })
console.log(`Hello ${process.env.HELLO}`)
```

```bash
DOTENV_PRIVATE_KEY_PRODUCTION="k78u3x_private_key_u6kweo" node ./test.js
```

**Comment by motdotla** [comment]
> That was unbelievably fast. Never have i seen someone respond fix and commit so quickly!

You're welcome.

> for some reason Railway doesnt seem to be recognizing all my variables unless i include the .env in source control

Railway has a gotcha in that they have a default `.railwayignore` file (hidden) that auto ignores a bunch of files - including .env files. Bad practice in my opinion. They should respect the `.gitignore` and the `.dockerignore` files.

here's a guide: https://dotenvx.com/docs/platforms/railway

```
# .railwayignore
.env.keys
!.env.production
``
