### ISSUE TITLE
"Decrypting" an empty string returns encrypted text, instead of plain text empty string.

### ISSUE THREAD

**Issue by happyjamstack** [dotenvx/dotenvx#234]
The following excerpt from the `README` works fine, so long as the string is not ''
```bash
$ dotenvx set HELLO World --encrypt
$ echo "console.log('Hello ' + process.env.HELLO)" > index.js

$ dotenvx run -- node index.js
[dotenvx] injecting env (2) from .env
Hello World
```

Here is where it goes wrong:
```
$ dotenvx set HELLO '' --encrypt
$ dotenvx run -- node index.js
HELLO encrypted:46HKO5...<big_long_ciphertext>...Q18Vb
```

Bash zero strings are impossible, I think, its just zero input? I'm not sure how `.env` is supposed to handle it, but I assume we _do_ want zero strings to be possible. I don't actually need this. It's just something i noticed and thought you would want to know. I'm using `0.44.0`

**Comment by motdotla** [comment]
good catch. yes we definitely want zero strings. will patch up as soon as possible. until then just manually modify. 

On Sun, May 26, 2024, at 7:49 AM, happyjamstack wrote:
> 
> 
> The following excerpt from the README works fine, so long as the string is not ''
> 
> $ dotenvx set HELLO World --encrypt
> $ echo "console.log('Hello ' + process.env.HELLO)" > index.js
> 
> $ dotenvx run -- node index.js
> [dotenvx] injecting env (2) from .env
> Hello World
> Here is where it goes wrong:
> 
> `$ dotenvx set HELLO '' --encrypt
> $ dotenvx run -- node index.js
> HELLO=encrypted:46HKO5...Q18Vb
`

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/236

going out as 0.44.1
