### ISSUE TITLE
How to pass values in to a docker compose?

### ISSUE THREAD

**Issue by nullbio** [dotenvx/dotenvx#235]
For example:

```  redis:
    <<: *common-main
    build:
      target: redis
      args:
        <<: *common-args
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS}"
          memory: "${DOCKER_REDIS_MEMORY}"
    profiles:
      - "redis"
```

How can I have it fetch the cpus and memory env vars from my .env file?

**Comment by motdotla** [comment]
use dotenvx get

dotenvx get DOCKER_REDIS_CPUS

see the github guide for including dotenvx in github actions:

https://dotenvx.com/docs/cis/github-actions

On Sun, May 26, 2024, at 5:39 PM, nullbio wrote:
> 
> 
> For example:
> 
> `    <<: *common-main
>     build:
>       target: redis
>       args:
>         <<: *common-args
>     deploy:
>       resources:
>         limits:
>           cpus: "${DOCKER_REDIS_CPUS}"
>           memory: "${DOCKER_REDIS_MEMORY}"
>     profiles:
>       - "redis"
`

**Comment by nullbio** [comment]
Thank you. For the case of scripts needing to pull env vars at runtime, that aren't passed through "environment:" in the compose.yml, I imagine it's a case of bind mounting the .env file, installing dotenvx in the image, and running the scripts inside the container through dotenvx run? Or in the case of not using a bind mount, building the .env file into the image itself alongside the addition of the dotenvx binary?

**Comment by motdotla** [comment]
@nullbio i think you're right.

but if you do want an example of installing dotenvx in the image, there is one here: https://dotenvx.com/docs/platforms/docker

Would be great if you could post a bit of script/code on your approach. Using that, I'll try to get a more complete Docker guide written on that approach up on our docs soon.

**Comment by nullbio** [comment]
Here's my thoughts on the whole process:

https://dev.to/nullbio/dotenvx-with-docker-the-better-way-to-do-environment-variable-management-5c0n

And a script I created to help with the workflow (discussed in the article):

https://github.com/nullbio/dotenvx-watcher

**Comment by harrytran998** [comment]
This is for anyone who faces this problem but wants to work around it simply. Just do:

1. Create decrypt env file + allow it executable. I use bun to install `dotenvx`, so depending on your choices, this can be changed. Remember to add gitignore for `.env*.decrypted` files.
```bash
tee -a decrypt-env.sh << EOF
#!/usr/bin/env bash
envFile="$1"
value=\$(bun dotenvx get -f \$envFile)

echo \$value | jq -r 'to_entries[] | .key + "=" + (.value|tostring) + ""' >> \$envFile.decrypted
EOF
chmod +x decrypt-env.sh
```
2. Decrypt the file you want
```bash
decrypt-env.sh .env.(name_your env here if have)
```
3. In the docker-compose file, in a service, you should add the env_file like below:

```yaml
  minio:
    image: bitnami/minio:latest
    env_file:
      - .env.decrypted
```

**Comment by nullbio** [comment]
> This is for anyone who faces this problem but wants to work around it simply. Just do:
> 
>     1. Create decrypt env file + allow it executable. I use bun to install `dotenvx`, so depending on your choices, this can be changed. Remember to add gitignore for `.env*.decrypted` files.
> 
> 
> ```shell
> tee -a decrypt-env.sh << EOF
> #!/usr/bin/env bash
> envFile="$1"
> value=\$(bun dotenvx get -f \$envFile)
> 
> echo \$value | jq -r 'to_entries[] | .key + "=" + (.value|tostring) + ""' >> \$envFile.decrypted
> EOF
> chmod +x decrypt-env.sh
> ```
> 
>     2. Decrypt the file you want
> 
> 
> ```shell
> decrypt-env.sh .env.(name_your env here if have)
> ```
> 
>     3. In the docker-compose file, in a service, you should add the env_file like below:
> 
> 
> ```yaml
>   minio:
>     image: bitnami/minio:latest
>     env_file:
>       - .env.decrypted
> ```

You're better off using the bash script I created, in the previous post:

* It stores the decrypted file in a more secure location and handles clean-up, it doesn't need to be gitignored because it's not in your project dir
* It handles changes to your encrypted file in real time and watches your files for changes (i.e. updates the decrypted file on change to the encrypted file)
* It doesn't need to be run multiple times

**Comment by benjaminbauer** [comment]
FWIW: both approaches can be simplified by removing `jq`. Just use `dotenvx get ... --format shell`

**Comment by motdotla** [comment]
oh yeah good thinking and thanks for the update here @benjaminbauer. `--format shell` is a recent addition that allows for simplifying this now.
