### ISSUE TITLE
$ (dollar) signs not handled properly in env var values

### ISSUE THREAD

**Issue by nullbio** [dotenvx/dotenvx#240]
I can't be 100% certain this isn't just a result of shell shenanigans whenever I try and introspect the values, but I'm fairly certain if you use $ in variable values, the env var value gets truncated at the first $.

```
pat@YODA:~/projects/dockertest$ cat .env.test
TESTVARA=this$is$a$test
TESTVARB='this$is$a$test'
TESTVARC="this$is$a$test"
pat@YODA:~/projects/dockertest$ dotenvx run -f.env.test -- sh -c 'echo $TESTVARA $TESTVARB $TESTVARC'
[dotenvx@0.44.1] injecting env (3) from .env.test
this this this
```

**Comment by decapo01** [comment]
I'm also having this issue from multiple shells

**Comment by abhikb101** [comment]
@decapo01 `\` works but is there any better way to do it?

**Comment by decapo01** [comment]
@abhikb101 Not that I'm aware of, but I don't have a lot of knowledge about this tool.  Just trying to clear my ticket out at work so I can move on to the next thing.

**Comment by musicjoeyoung** [comment]
For what it's worth I had the same issue, found this issue, and the `\` was the solution.

**Comment by motdotla** [comment]
any dollar signs will attempt to be interpolated/expanded unless escaped. for anyone who comes by this issue, just make sure to escape your dollar signs.
