### ISSUE TITLE
dotenvx run, flag to pass through the private key

### ISSUE THREAD

**Issue by nullbio** [dotenvx/dotenvx#241]
Right now dotenvx will load your .env.keys file automatically if the file is present in the directory of the env file, and serve the decrypted contents to the subprocess. For example:

.env.production with encrypted env var
.env.keys with .env.production private key

`dotenvx run -f.env.production -- sh -c 'echo "$ENCRYPTED_VAR"'` will output the decrypted value.

This works well for subprocesses that need to access decrypted values without requiring the private key directly, but if you're using this in a containerized fashion with docker compose, you run in to the following scenario:

`dotenvx run -f.env.production -- env PRIVKEY=<your private key> docker compose up service`

And in your compose file you end up with:

`command: sh -c "DOTENV_PRIVATE_KEY_PRODUCTION=$PRIVKEY exec dotenvx run -o -f/app/.env.production -- process"`

Because Docker Compose needs to pass in the value of $PRIVKEY from the hosts environment, to the command running in the container, so the containers dotenvx can decrypt the values obtains from the bind mounted .env file (in this case, the bind mount is: `.env.production:/app/.env.production`.)

It would be helpful if we could tell dotenvx to also pass along the private key for us, by injecting it as an additional env var, since it has likely already fetched it from your .env.keys file, for example:

`dotenvx run -f.env.production --passthrough-priv-key -- docker compose up service`

This is nice because it allows us to avoid having to manually get the key and insert it (which may also end up being saved in files if you're running docker compose through some wrapper scripts). It also prevents the private key from being logged in bash history if you're running this via the shell. 

An even better way to deal with all of this has been requested as a feature here, which also outlines some problems in depth I've been facing with the workflow: https://forums.docker.com/t/docker-compose-argument-to-replace-env-file-directive-or-argument-to-enable-host-environment-passthrough/141671 -- but who knows how receptive they will be to this, and when it could possibly be supported.

**Comment by motdotla** [comment]
hey @nullbio if `dotenvx` is already installed in the Dockerfile (inside of docker-compose), can you just do this?

```
$ DOTENV_PRIVATE_KEY_PRODUCTION=$PRIVKEY docker compose up service
```

or for extra security (avoiding bash history):

```
# docker-compose.yml
version: '3.8'
services:
  myservice:
    image: myimage
    environment:
      - DOTENV_PRIVATE_KEY_PRODUCTION=${PRIVKEY}
```

does that work?

**Comment by nullbio** [comment]
I don't believe so. Fairly certain that's only used to pass environment variables to the build image at build time, not to pass environment variables to an already built image during the service start. You'd have to double check to be certain though, it's been a while since I played with all of this and my memory is a little fuzzy.

**Comment by svallory** [comment]
@nullbio @motdotla this is not related to dotenv. The variables will passthrough if defined. You only need to intervene if the variable was not set anywhere in the dockerfile or the compose file.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/453a09c9-b69b-4fd5-aaf7-39d1c9e72ed7">

**Comment by nullbio** [comment]
@svallory That only works for docker-compose exec though, not up. Up does not have an -e arg.

**Comment by svallory** [comment]
@nullbio you are right. But you only need the `-e` if the variable was not specified anywhere. If you add `- DOTENV_PRIVATE_KEY_PRODUCTION` to the docker-compose `environment:` key without any value, and you have that in your `.env` file, it will pass through.

Look at the `COMPOSE_PASS_NO_VAL` in the example

**Comment by nullbio** [comment]
@svallory That's happening at build time though. It exists at runtime because it's set at build time, permanently, in the image. Try changing the value of `COMPOSE_PASS_NO_VAL` in your dotenv.env file after you've built the image.

**Comment by svallory** [comment]
@nullbio I think you are mistaken. Check the test below. Also, you may want to check Docker's [environment variable precedence docs](https://docs.docker.com/compose/environment-variables/envvars-precedence/)

```
projects/test-work/docker-vars on 🐳 v27.0.3 runs 🐙 DDDD
➜ cat dotenv.env; dotenvx run -f dotenv.env -- \
    docker compose build
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: dotenv.env
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ COMPOSE_PASS="set from dotenv .env"
   2   │ COMPOSE_PASS_VAL="set from dotenv .env"
   3   │ COMPOSE_PASS_NO_VAL="set from dotenv .env"
   4   │ __UNKNOWN_VAR__="set from dotenv .env"
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[dotenvx@1.6.4] injecting env (4) from dotenv.env
[+] Building 0.1s (9/9) FINISHED                                                                                                                          docker:desktop-linux
 => [flox internal] load build definition from Dockerfile                                                                                                                 0.0s
 => => transferring dockerfile: 365B                                                                                                                                      0.0s
 => WARN: JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 15)                                          0.0s
 => [flox internal] load metadata for ghcr.io/flox/flox:latest                                                                                                            0.0s
 => [flox internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                           0.0s
 => [flox 1/4] FROM ghcr.io/flox/flox:latest                                                                                                                              0.0s
 => [flox internal] load build context                                                                                                                                    0.0s
 => => transferring context: 35B                                                                                                                                          0.0s
 => CACHED [flox 2/4] RUN mkdir /code                                                                                                                                     0.0s
 => CACHED [flox 3/4] COPY print_vars.sh /code/print_vars                                                                                                                 0.0s
 => CACHED [flox 4/4] RUN chmod 777 /code/print_vars                                                                                                                      0.0s
 => [flox] exporting to image                                                                                                                                             0.0s
 => => exporting layers                                                                                                                                                   0.0s
 => => writing image sha256:468cfb5ff2b77cf0bfd62a6f0e7936719852719107d59f5fd67f3d75ddb38e9f                                                                              0.0s
 => => naming to docker.io/library/docker-vars-flox                                                                                                                       0.0s

projects/test-work/docker-vars on 🐳 v27.0.3 runs 🐙 DDDD
➜ sed -i '' 's/COMPOSE_PASS_NO_VAL="set from dotenv .env"/COMPOSE_PASS_NO_VAL="UPDATED"/' dotenv.env; cat dotenv.env
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: dotenv.env
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ COMPOSE_PASS="set from dotenv .env"
   2   │ COMPOSE_PASS_VAL="set from dotenv .env"
   3   │ COMPOSE_PASS_NO_VAL="UPDATED"
   4   │ __UNKNOWN_VAR__="set from dotenv .env"
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

projects/test-work/docker-vars on 🐳 v27.0.3 runs 🐙 DDDD
➜ dotenvx run -f dotenv.env -- \
    docker compose run flox
[dotenvx@1.6.4] injecting env (4) from dotenv.env
total 4
-rwxrwxrwx 1 root root 693 Jul 26 23:45 print_vars
flox collects basic usage metrics in order to improve the user experience.

flox includes a record of the subcommand invoked along with a unique token.
It does not collect any personal information.

The collection of metrics can be disabled in the following ways:

  environment: FLOX_DISABLE_METRICS=true
    user-wide: flox config --set-bool disable_metrics true
  system-wide: update /etc/flox.toml as described in flox(1)

This is a one-time notice.


✨ Created environment 'code' (aarch64-linux)

Next:
  $ flox search <package>    <- Search for a package
  $ flox install <package>   <- Install a package into an environment
  $ flox activate            <- Enter the environment
  $ flox edit                <- Add environment variables and shell hooks


🚀  Flox has a new version available. 1.2.2 -> 1.2.3

Get the latest at https://flox.dev/docs/install-flox/#upgrade-existing-flox-installation

✅ 'gum' installed to environment 'code'
╭─────────────────────┬───────────────────────────────────────╮
│ Variable            │ Value                                 │
├─────────────────────┼───────────────────────────────────────┤
│ HELLO_ENV_VARIABLE  │ Hello from Dockerfile                 │
│ HELLO_BUILD_ARG     │ Hello from docker-compose build args  │
│ HELLO_MESSAGE       │                                       │
│ HELLO_COMPOSE_ENV   │ Hello from docker-compose environment │
│ COMPOSE_ONLY        │ Set only in compose                   │
│ COMPOSE_PASS        │ Passing through set from dotenv .env  │
│ COMPOSE_PASS_VAL    │ set from dotenv .env                  │
│ COMPOSE_PASS_NO_VAL │ UPDATED                               │
│ __UNKNOWN_VAR__     │                                       │
╰─────────────────────┴───────────────────────────────────────╯
```

**Comment by nullbio** [comment]
I'm referring to how env vars are set in the image when using the `docker compose up` command. The `run` and `exec` are both different in that they allow you to pass in run-time env vars, however docker compose up gives you no method to do that as far as I'm aware? Can you recreate the same result after changing the value in the env file when using `docker compose up`?

**Comment by svallory** [comment]
@nullbio It makes no difference if you use `run` or `up`. You can check the code here: https://github.com/svallory/docker-variable-precedence

<img width="2227" alt="image" src="https://github.com/user-attachments/assets/e4d50c94-56d0-49ff-9907-de559358fb3e">

**Comment by nullbio** [comment]
It seems you are right, I stand corrected! Thanks for uploading the demo.

**Comment by motdotla** [comment]
thanks everyone for the discussion and for digging in so deeply. closing.
