### ISSUE TITLE
Make `set KEY --encrypt` support reading value from `.env`

### ISSUE THREAD

**Issue by bingtsingw** [dotenvx/dotenvx#243]
`.env` file
```
JWT="xxxxx"
```

Now we have to use `dotenvx set KEY "xxxx" --encrypt`, it will be much easier and safer to write the unencrypted value into the .env file and then use `dotenvx set KEY --encrypt` to `read set set` it

**Comment by motdotla** [comment]
did you mean to say it would be safer to default to encryption on? and instead have a --raw flag or something?

**Comment by bingtsingw** [comment]
Default to encryption on maybe not safe, and it's a breaking change to the current behavior which throws an error if not presenting a value.

`--raw` looks like a good idea, but if we want to support `--decrypt`, the api is a little strange.
`dotenvx set KEY --encrypt  --raw`: read KEY from .env and encrypt
`dotenvx set KEY --decrypt  --raw`: read KEY from .env and decrypt
`dotenvx set KEY 123 --encrypt`: decrypt 123 and set KEY
`dotenvx set KEY 123 --decrypt`: **THIS COMMAND MAKES NO SENSE**

Maybe we can make a new command for this behavior, such as
`dotenvx new-command KEY --encrypt`
`dotenvx new-command KEY --decrypt`

**Comment by aqeelat** [comment]
I think the value here is to not write the secret in the terminal because it will be stored in the history.

**Comment by bingtsingw** [comment]
> I think the value here is to not write the secret in the terminal because it will be stored in the history.

Yes, that's exactly one of my concerns, besides, it's more convenient to convert a `.env` to a half decrypted version, such as:
<img width="234" alt="image" src="https://github.com/dotenvx/dotenvx/assets/10382462/7e6fffa2-cab9-4d6c-b7da-cbc0b32e0db5">

**Comment by motdotla** [comment]
why are you suggesting a --decrypt flag? there is dotenvx get KEY for that.

**Comment by AlissonRS** [comment]
Hi, I'm new to dotenvx. I like the idea proposed.

As devs add new secrets to the .env.ci, their peer devs can easily decrypt the .env.ci into their local .env (which is not pushed to git).

They could also easily add new secrets to their local .env file, and encrypt it into .env.ci without having to specify the actual keys in the terminal.

In short, encryption/decryption could both have input/output files that can be different: `dotenvx encrypt --input .env --output .env.ci` or something similar.

**Comment by motdotla** [comment]
ah, i see, i misunderstood your first question. 

you can use `convert` for this:

```
dotenvx convert
```

https://github.com/dotenvx/dotenvx#advanced-usage

(this command will likely get renamed to `dotenvx encrypt` in the 1.0.0 release)

does that solve all your needs here?

**Comment by bingtsingw** [comment]
`convert` works for a whole file, can it work for only one `KEY`

**Comment by motdotla** [comment]
ah, sorry this took me so long to grok. i understand the need now.

at the moment i think the better place to put this is under `convert` and add an optional flag to specify a single (or array) of `KEY`s to convert/encrypt, but let me think on this one a bit.

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/281

going out as part of `1.3.0` release
