### ISSUE TITLE
How to use GitHub Actions with vault files

### ISSUE THREAD

**Issue by AlissonRS** [dotenvx/dotenvx#244]
Hi!

@motdotla thanks for such a great package.

I'm trying to get started using this with GitHub Actions. I saw the The docs for [GitHub Actions](https://dotenvx.com/docs/cis/github-actions) which shows an example of creating an `.env.ci` file, but manually adding keys is a tedious work.

So I looked for a way to encrypt an entire `.env` file (so I don't have to manually add each key), then I found `dotenvx vault encrypt` to generate a `.env.vault` file and pushed this to github since it's encrypted.

Then on GitHub Actions, I tried using it like this:
```
      - name: Deploy
        env:
            DOTENV_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
        run: |
          dotenvx run -- yarn deploy
```
The `DOTENV_PRIVATE_KEY` in GitHub Secrets was filled with the vault private key (DOTENV_KEY_DEVELOPMENT), e.g. `dotenv://:key_aaaaaa@dotenvx.com/vault/.env.vault?environment=development` (I don't really understand where does "environment=development" in the private key come from since nowhere I defined an environment name).

However this throws a warning:

> DEPRECATION NOTICE: Setting DOTENV_KEY with .env.vault is deprecated.
> DEPRECATION NOTICE: Run [dotenvx vault convert] for instructions on converting your .env.vault file to encrypted .env files (using public key encryption algorithm secp256k1)

Following the instructions, I ran `dotenvx vault convert` which gave me this output:
```
To convert your .env.vault file to encrypted .env file(s):

  1. Run [dotenvx vault decrypt]
  2. Run [ls -a .env*]

Lastly, convert each .env(.environment) file:

  3. Run [dotenvx convert -f .env.production]

For example:

  $ dotenvx convert -f .env
  $ dotenvx convert -f .env.ci
  $ dotenvx convert -f .env.production

Afterward:

Update production with your new DOTENV_PRIVATE_KEY_PRODUCTION located in .env.keys
```

Running `dotenvx convert -f .env.ci` doesn't work because there is no `.env.ci` file, only a `.env.vault` file.

So running `dotenvx convert -f .env.vault` will do a few things:

- Add a `DOTENV_PRIVATE_KEY_VAULT` to the .env.keys
- Update the `DOTENV_VAULT_DEVELOPMENT` in the .env.vault
- Add a `DOTENV_PUBLIC_KEY_VAULT` in the .env.vault

This just made me confused, it's unclear if the `convert` command is meant to work together with vault, and how this can help me use this on GitHub Actions without the deprecation warning.

So a few questions:

1) Why does it update `DOTENV_VAULT_DEVELOPMENT`? Wasn't it already encrypted with the `DOTENV_KEY_DEVELOPMENT` (the key that starts with `dotenv://:key_a`)?
2) Why do we need two private keys, `DOTENV_KEY_DEVELOPMENT` and `DOTENV_PRIVATE_KEY_VAULT`?
3) How can I use this package in GitHub Actions without having to add key by key manually to a `.env.ci` file?

I also tried using `DOTENV_PRIVATE_KEY_CI` instead of `DOTENV_KEY` but it doesn't seem to work with vaults, as it's expecting the `.env.ci` file (which I don't have), I don't know how to convert `.env.vault` to `.env.ci` (is that even possible?).

Hopefully this summarizes all pain points of a newbie trying to get started using this awesome library :sweat_smile:

**Comment by motdotla** [comment]
hi @AlissonRS. 

sorry about this and thanks for the feedback. 

you happened to read our docs when they were out of date. 

they are updated now here:

https://dotenvx.com/docs/cis/github-actions

DONT use the .env.vault mechanism. it is now deprecated

1. create your .env.ci
2. encrypt it with `dotenvx convert` or `dotenvx set KEY value --encrypt`
3. set the private key on your github actions ci. 

delete your .env.vault file

**Comment by AlissonRS** [comment]
@motdotla thanks for the quick response legend :pray: 

I'm assuming I can just duplicate the `.env` file, rename it to `.env.ci` then `dotenvx convert` right?

Should be simple enough to create a script in `package.json` so my team can easily update the `.env.ci` as they add new secrets to their local `.env` file. I'll try this approach.

Thanks again!
