### ISSUE TITLE
Should we be using dotenvx or dotenv-vault?

### ISSUE THREAD

**Issue by Martinsos** [dotenvx/dotenvx#245]
Hi,
thanks for all the awesome work with dotenv!

I just recently started using dotenv-vault, as I saw it recommended on the dotenv npm package. But now I realized that there is also dotenvx, and it seems to me like it is supposed to be the newer, better solution, a succession to dotenv-vault? Is this correct, should I be using dotenvx instead?
I just started so I can easily switch, but will probably be putting quite few more projects on it + probably recommending it as a default method for https://wasp-lang.dev/, so I wouldn't want to go all in on dotenv-vault if it is deprecated.

Thanks!

**Comment by motdotla** [comment]
wasp-lang looks great! (I'm a longtime user of Rails and it does a lot of things right, things still missing from the node community)

yes, switch to dotenvx. 

1. it is replacing dotenv and works the same everywhere
2. it maintains all the initial benefits of dotenv-vault without requiring a 3rd party cloud service to be up and running. (it's just cli tooling to generate .env files and corresponding private/public key pairs)

**Comment by Martinsos** [comment]
Thanks, we are working hard on it, and quite excited about the future! Indeed, RoR has that unique DX that people love and is a big inspiration.

Awesome, we will switch to dotenvx. I guess you have probably thought of putting some kind of banner or notice on dotenv-vault webpage/repo to send people over to dotenvx, but didn't have time yet to get to it? I think it would help in my case, I was actively looking for such notice once I figure out there are two but couldn't find one which made me ask the question to clear the air.

**Comment by motdotla** [comment]
> putting some kind of banner or notice on dotenv-vault webpage/repo to send people over to dotenvx, but didn't have time yet to get to it

yes, mostly this.

i'm very aware the offering is confusing right now, but we're not quite there to providing a migration path. `dotenvx` is almost ready for 1.0.0 and then we'll go hard into providing a migration path from `dotenv-vault` to `dotenvx`.

with that, we have to build some opt-in team features. dotenv-vault has pretty good team features and dotenvx currently has none. until then, we're recommending you manage dotenvx private keys with 1password or something similar.

**Comment by Martinsos** [comment]
Got it! Yeah, team features are certainly valuable, it is in big part what I liked about dotenv-vault, that I just add team members on it, they can authenticate, and it all works.

Sounds good, looking forward to it, and thanks again for quick response!
