### ISSUE TITLE
Using dotenvx is complicated due to missing features compared to dotenv-vault

### ISSUE THREAD

**Issue by aminya** [dotenvx/dotenvx#246]
With the [recent changes](https://github.com/dotenvx/dotenvx/blob/main/CHANGELOG.md#0380) in `dotenvx`, using it is harder than ever. Previously, dotnv-vault would create a `.dotenv.vault` file that had the same format for both CLIs, but now, `dotenvx` uses a different format and encryption algorithm. This means that using the UI of dotenv.vault and sharing keys between team members is harder than before.

It seems that I should run all these commands and do some external work to be able to simply use dotenvx with encryption:

```shell
npx -y dotenv-vault new -y
npx -y dotenv-vault login -y
npx -y dotenv-vault open -y

# modify the .env files in the web UI
# then:

envs=("development" "production" "staging" "ci")
for env in "${envs[@]}"; do
        npx -y dotenv-vault pull $env .env.$env
        npx -y dotenvx vault encrypt -f .env.$env
done

# figure out a way to share `.env.keys` with your team as it is no longer possible to use the `dotenv-vault` CLI to pull the keys

# later to run the app:

source ./.env.keys
DOTENV_KEY=$DOTENV_KEY_DEVELOPMENT npx -y dotenvx run -- node -e "console.log(process.env)"
```

Is this really the intended workflow? Or am I missing something in the process?

For now, I have pinned `dotenvx` to  ` "@dotenvx/dotenvx": "0.37.1"` to avoid this complicated workflow. But I would appreciate it if there's a better way.

Also, the change in the encryption algorithm means all the tooling for different programming languages such as [dotenv-vault-rs](https://github.com/Minebomber/dotenv-vault-rs/) is not usable. I personally prefer not to install Nodejs just to be able to set environment variables in my Rust containers.

**Comment by motdotla** [comment]
yes, i'm so sorry about this. we're aware the offering is confusing right now. we even tweeted about it when someone thought one might be a scam: https://x.com/dotenvx/status/1778443989521432906

bear with us a little longer. `dotenvx` is almost at 1.0.0 and then we'll be providing a migration path from dotenv-vault to dotenvx.

until then, you should choose one or the other.

1. if team features are currently important to you, just use dotenv-vault and follow the docs at dotenv.org/docs
2. if using the latest solution is more important to you, use `dotenvx` and follow the docs at dotenvx.com/docs

in time (over the next 6 months) dotenvx will add team features. until then, we recommend managing your private keys across your team using 1password or something similar.

so for your case, if you want to switch to `dotenvx`:

1. convert all your `.env.vault` files to `.env*` files using `dotenv-vault decrypt`
2. then use dotenvx to convert those to encrypted .env files `dotenvx convert`
3. then shut down your team account at dotenv.org. it does not support sharing/displaying encyrpted .env files.

does this make sense? sorry again for this confusing setup at the moment. we learned a lot from dotenv-vault and basically are committing to dotenvx going forward as a result. it offers a better full solution to the community to those who need a free and non-hosted solution that meets most needs. and then we can add in a paid set of team features on top of it over the next 6 months and more.
