### ISSUE TITLE
dotenvx install failed in github actions

### ISSUE THREAD

**Issue by veaceslavkuhn** [dotenvx/dotenvx#252]
<img width="726" alt="Screenshot 2024-06-18 at 09 43 52" src="https://github.com/dotenvx/dotenvx/assets/17174508/d1def3be-6ec2-4cd6-bd93-5510a8268ac3">

Hello, since 6-7 hours ago, the installation of dotenvx in my GitHub actions workflow started failing with an error that you can see on the screenshot. Is it related to the latest release or is it an issue on my end?

**Comment by motdotla** [comment]
it was related to using a bash mechanism `[[` inside a `sh`. 

We patched it up within 30 minutes so maybe github actions has it cached somehow. Try changing to either of the following:


```
curl -fsS https://dotenvx.sh | bash
```

```
curl -fsS https://dotenvx.sh/install.sh | sh
```

**Comment by veaceslavkuhn** [comment]
It works now. Thank you for a quick fix
