### ISSUE TITLE
Allow config file

### ISSUE THREAD

**Issue by nahtnam** [dotenvx/dotenvx#261]
Thoughts on allowing a `.env.config` file or something that lets us define default flags? In my case I'd like everything encrypted all the time without having to type `--encrypt` every time (or potentially forgetting to put the flag)

**Comment by motdotla** [comment]
as of `1.0.0` it encrypt by default when using `dotenvx set KEY value`. You no longer need to pass `--encrypt`.

> Thoughts on allowing a .env.config file or something that lets us define default flags?

Interesting, I think it might be a bit early, and that instead we might have project or user based defaults. There is a `dotenvx ext settings` extension that is currently largely unused but could bring in this kind of functionality.

**Comment by nahtnam** [comment]
Awesome, I missed that on the patch notes. Thank you!

I can see people who want something like `--convention=nextjs` by default want this feature too
