### ISSUE TITLE
curl oneliner - should it default to `sudo` ?

### ISSUE THREAD

**Issue by insanity54** [dotenvx/dotenvx#262]
Hi thanks for dotenvx. I'm a long-time user of dotenv and dotenvx is just what I've been craving. I often worry about leaking my .env file and the encryption feature of dotenvx will help me sleep at night.

When trying out dotenvx, I noticed one small issue with the curl oneliner. It attempts to install to /usr/local/bin which is not writable.

```
curl -sfS https://dotenvx.sh | sh
[INSTALLATION_FAILED] the installation directory [/usr/local/bin] is not writable by the current user
? run as root [curl -sfS https://dotenvx.sh | sudo sh] or choose a writable directory like your current directory [curl -sfS "https://dotenvx.sh?directory=." | sh]
```

```
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	24.0.2
Codename:	Wynsdey
```

I think one fix is to pipe to `sudo sh` instead of just `sh`. Another possible solution (my preference) is to install only for the current user in a place on their PATH, like `~/.local/bin/`, but I'm not sure if the install script is setup for that. Anyway, just my 2 sats. Thanks again.

**Comment by motdotla** [comment]
> Hi thanks for dotenvx. I'm a long-time user of dotenv and dotenvx is just what I've been craving. I often worry about leaking my .env file and the encryption feature of dotenvx will help me sleep at night.

Great! you're very welcome @insanity54.

> I think one fix is to pipe to sudo sh instead of just sh

Indeed, but for now I think it's best the user choose to use sudo than we default to it. What do you think?

The help text outputted instructs almost exactly this:

```
? run as root [curl -sfS https://dotenvx.sh | sudo sh] or choose a writable directory like your current directory [curl -sfS "https://dotenvx.sh?directory=." | sh]
```

maybe we should make it clearer?

**Comment by insanity54** [comment]
> ? run as root [curl -sfS https://dotenvx.sh | sudo sh] or choose a writable directory like your current directory [curl -sfS "https://dotenvx.sh?directory=." | sh]

I completely missed this help text when I first installed. I think it's good like this :smile:

**Comment by motdotla** [comment]
maybe rather than using the question mark we should have `[try this]:` or something like that, that is more eye catching. the eye sort of sees the `[INSTALLATION_FAILED]` and because it is so dominant stops reading (i think)

**Comment by motdotla** [comment]
going to stick with the `?`. `[HELP]`, `[TO FIX]`, etc all look visually too heavy when trying them out locally on my machine.
