### ISSUE TITLE
End user error from `v1.2.0`

### ISSUE THREAD

**Issue by NamesMT** [dotenvx/dotenvx#282]
Commit 5578ee006141a2c44db0a3fa572fd7055e6fc66b added the `postinstall` script, which when end user install `dotenvx`, the script will try to run and fail.

**Comment by Peyman-Borhani** [comment]
@motdotla It seems `patch-package` is not found, maybe it should be in `dependencies` instead of devDependencies?

btw what patch-package patches at this point? 
Is it required by dotenvx to remain functional? (after postinstall)

**Comment by SuperchupuDev** [comment]
patch-package patches a dev dependency. ideally this shouldn't be a normal dependency. patch-package shouldn't be called on postinstall

**Comment by motdotla** [comment]
apologies for this everyone. @SuperchupuDev thank you for the patch.

releasing as 1.2.1 shortly

**Comment by motdotla** [comment]
it is not used for the npm module, but it is needed in order to properly build the binaries for linux, mac, and windows. 

i'm adding a postinstall step to our ci to make sure if this happens again I know about it sooner.

**Comment by motdotla** [comment]
correction `1.3.2`

```
npm install @dotenvx/dotenvx@1.3.2 --save
```
