### ISSUE TITLE
high cpu usage issue

### ISSUE THREAD

**Issue by joonior** [dotenvx/dotenvx#284]
hi
after I run this command in my project `dotenvx encrypt` on my device (apple silicon chip M1 pro) , a process runs on my system which I took a snapshot of it
![Screenshot 2024-06-30 at 16 19 23](https://github.com/dotenvx/dotenvx/assets/12700764/4c60b082-ee11-435b-9d2f-7f28581c532e)

same issue when I ran this on docker.

is it a known issue??? how can I fix this issue?

**Comment by motdotla** [comment]
this is related to checking for updates - a convenience for users to remind them to update to new versions.

does this process stop after 30 seconds?

isn't the cpu uage here 0% though? or am i reading your pid list incorrectly?

**Comment by motdotla** [comment]
i've opted to remove the updateNotice completely. i don't want to nag users to install the latest version. let them decide.

https://github.com/dotenvx/dotenvx/pull/288

will go out as 1.4.0 - also solving this possible cpu issue for anyone who might have experienced it.

**Comment by andrelaszlo** [comment]
I just killed a bunch of dotenvx processes (`/snapshot/dotenvx/src/lib/helpers/updateNotice/check.js`) with all cores at 100%. I'm on `dotenvx-1.3.2-darwin-arm64`.

**Comment by motdotla** [comment]
apologies for this. can you try `1.4.0`. it removed the updateNotice/check which was being spawned too often. there are no update checks now.

**Comment by motdotla** [comment]
```
curl -sfS https://dotenvx.sh/?version=1.4.0
```

**Comment by andrelaszlo** [comment]
Each time I run dotenvx, two new checker processes start in the background. They seem to be replaced quite frequently:

<details>
<summary>Reproducing</summary>

```
⮕ pkill -9 envx                                                
~ 2024-06-30T20:58:10+00:00 
⮕ dotenvx --help >/dev/null
~ 2024-06-30T21:08:20+00:00 
⮕ time (for i in $(seq 100); do ps aux | grep snapshot | grep -v grep ; done) > /tmp/dotenvx.log
( for i in $(seq 100); do; ps aux | grep --color snapshot | grep --color -v ;  1.33s user 3.58s system 104% cpu 4.714 total
~ 2024-06-30T21:08:39+00:00 
⮕ cat /tmp/dotenvx.log | awk '{print $2}' | sort | uniq | wc -l
      53
~ 2024-06-30T21:08:48+00:00 
⮕ dotenvx --help >/dev/null                                                                     
~ 2024-06-30T21:08:55+00:00 
⮕ dotenvx --help >/dev/null
~ 2024-06-30T21:08:56+00:00 
⮕ dotenvx --help >/dev/null
~ 2024-06-30T21:08:57+00:00 
⮕ time (for i in $(seq 100); do ps aux | grep snapshot | grep -v grep ; done) > /tmp/dotenvx.log
( for i in $(seq 100); do; ps aux | grep --color snapshot | grep --color -v ;  1.85s user 5.18s system 89% cpu 7.831 total
~ 2024-06-30T21:09:19+00:00 
⮕ cat /tmp/dotenvx.log | awk '{print $2}' | sort | uniq | wc -l                                 
     195
~ 2024-06-30T21:09:23+00:00 
⮕ dotenvx --help >/dev/null                                                                     
~ 2024-06-30T21:09:31+00:00 
⮕ dotenvx --help >/dev/null
~ 2024-06-30T21:09:32+00:00 
⮕ dotenvx --help >/dev/null
~ 2024-06-30T21:09:33+00:00 
⮕ time (for i in $(seq 100); do ps aux | grep snapshot | grep -v grep ; done) > /tmp/dotenvx.log
( for i in $(seq 100); do; ps aux | grep --color snapshot | grep --color -v ;  1.92s user 5.41s system 91% cpu 8.044 total
~ 2024-06-30T21:09:44+00:00 
⮕ cat /tmp/dotenvx.log | awk '{print $2}' | sort | uniq | wc -l                                 
     207
~ 2024-06-30T21:09:49+00:00 
⮕ pkill -9 envx                                                
~ 2024-06-30T21:09:51+00:00 
⮕ time (for i in $(seq 100); do ps aux | grep snapshot | grep -v grep ; done) > /tmp/dotenvx.log
( for i in $(seq 100); do; ps aux | grep --color snapshot | grep --color -v ;  1.21s user 3.22s system 101% cpu 4.362 total
~ 2024-06-30T21:11:15+00:00 
⮕ cat /tmp/dotenvx.log | awk '{print $2}' | sort | uniq | wc -l                                 
       0
```

</details>

The `kernel_task` seems to be using most of the CPU, so I guess it's some kind of system call, but I haven't debugged it at all.

Adding this info in case it's an issue with the command itself, but I guess it's probably solved by removing the update notice check 👍
