### ISSUE TITLE
CI and Prod in single file

### ISSUE THREAD

**Issue by RajeshPandey057** [dotenvx/dotenvx#310]
First of all thank you very much for this tool. It is truly the well deserving successor of dotenv. It has simplified a lot of stuff for me. That being said I need help with a particular scenario which I am sure is very normal one.

I have a github actions+docker setup to deploy a nextjs app where I am running docker build stage with 
```
--build-arg DOTENV_PRIVATE_KEY_CI=${{ secrets.DOTENV_PRIVATE_KEY_CI }}
``` 
which automatically pickups, decrypts and loads .env.ci inside Dockerfile for which I am doing this inside dockerfile
```
ARG DOTENV_PRIVATE_KEY_CI=privatekey
ENV DOTENV_PRIVATE_KEY_CI=${DOTENV_PRIVATE_KEY_CI}
.
.
.
RUN pnpm dlx @dotenvx/dotenvx run -- pnpm run build
.
.
.
CMD HOSTNAME="0.0.0.0" pnpm dlx @dotenvx/dotenvx run -- node server.js
``` 

Now my issue is I have a branch based CI configuration where depending upon which branch has the commit, either dev instance will be build and deployed or prod instance will be build and deployed. I was able to setup rest of things just dotenvx setup is pending. My expectation is based on a boolean that I passed to dockerbuild command, dotenvx should load either ```.env.ci``` file or ```.enc.production``` (or just ``` .env```) file so I can have same github action and Dockerfile in both branches. I tried few ways but not able to do so.

**Comment by motdotla** [comment]
i believe you just need to extend your Dockerfile to optionally accept the `DOTENV_PRIVATE_KEY_PRODUCTION`, so something like this?

```
ENV DOTENV_PRIVATE_KEY_CI=${DOTENV_PRIVATE_KEY_CI}
ENV DOTENV_PRIVATE_KEY_PRODUCTION=${DOTENV_PRIVATE_KEY_PRODUCTION}
.
.
.
RUN pnpm dlx @dotenvx/dotenvx run -- pnpm run build
.
.
.
CMD HOSTNAME="0.0.0.0" pnpm dlx @dotenvx/dotenvx run -- node server.js
```

this way if `_PRODUCTION` is set run will look for the `.env.production` file. If `_CI` is set it will look for `.env.ci`.

see if that works?

if not, i am considering the option to pass `--privateKey=<privatekey>` directly as a flag to `run`. this way, you could write code to compose your run command however you wish:

```sh
$ dotenv run -f .env.production --privateKey=<prodPrivKey> -- node server.js
$ dotenv run -f .env.ci --privateKey=<ciPrivKey> -- node server.js
etc
```

**Comment by motdotla** [comment]
going to close this, let me know if it doesn't work.

**Comment by RajeshPandey057** [comment]
Apologies I was busy last week and couldn't check it. Github secret are repository level, (branch/tag level secrets require premium 🙂‍↔️) so both CI and PRODUCTION secret would be set and dotenvx would decrypt both and load both. I am not sure which file will be loaded to env finally but still a little finicky approach.

Although second solution, Works like a charm. Exactly what I needed. I am creating two variables in docker like this

```YAML
dotenv run -f $FILE_NAME --privateKey=$KEY -- node server.js
```
 and based on the keyword ```dev``` in the commit tag I am passing either dev or production secrets in github actions to docker command.
 
 ```YAML
 if [ ${{ contains( github.ref_name,'dev') }} ]; then
            docker build --build-arg FILE_NAME=.env.ci  --build-arg KEY=${{ secrets.DOTENV_PRIVATE_KEY_PRODC }}  -t ${{ github.sha }} ./
          else
            docker build --build-arg FILE_NAME=.env.production--build-arg DOTENV_PRIVATE_KEY=${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }} -t ${{ github.sha }} ./
          fi
```

Also great release last week. Now I can use actual names like .env.dev and .env.prod instead of CI and PRODUCTION. Thanks for all your work ✨
