### ISSUE TITLE
Not compatible with webpack 5 due to dependency on winston

### ISSUE THREAD

**Issue by dmm9** [dotenvx/dotenvx#318]
It is not possible to have an app which uses dotenvx and which is bundled with Webpack, due to an issue in Winston. See [this issue](https://github.com/winstonjs/winston/issues/1919), which seems noone really cares about for more than 3 years.

![grafik](https://github.com/user-attachments/assets/17e46b71-0df4-4290-8844-d72aa609ef06)

So, for the moment, I am rolling back to dotenv.

**Comment by motdotla** [comment]
i'll consider removing winston, but I find it pretty great.

isn't this something webpack should fix? isn't this the point of webpack to solve these problems?

**Comment by motdotla** [comment]
pino looks interesting https://getpino.io/#/

**Comment by SuperchupuDev** [comment]
this sounds like something that can just be replaced by console.log with [`color-convert`](https://www.npmjs.com/package/color-convert) and a few checks..? pino is more for like http servers, probably too bloated considering the usage dotenvx has of loggers

**Comment by motdotla** [comment]
@SuperchupuDev maybe the node community needs a new light weight logger with colors? or what do you think of this? https://github.com/medikoo/cli-color

**Comment by SuperchupuDev** [comment]
hmm, cli-color looks rather big, it uses 14 dependencies, while color-convert uses one. the current standard for lightweight colors is `picocolors` but it doesn't support custom rgb values (which is what color-convert does). would be nice if picocolors supported it. meanwhile `chalk` which is used in dotenvx (and uses 5 dependencies) could be replaced with color-convert and picocolors?

**Comment by motdotla** [comment]
i've removed winston. @dmm9 can you try again with dotenvx `1.9.0` or greater. it's going out to npm now.

**Comment by dmm9** [comment]
Hi @motdotla , I tested with `1.10.2` and it compiles and works. Thanks! For future reference: solved with #347
