### ISSUE TITLE
Missing first newline when using command substitution

### ISSUE THREAD

**Issue by bijeebuss** [dotenvx/dotenvx#321]
#### .env
```
TEST="$(cat test.txt)"
```
#### test.txt
```
one
two
three
```
#### command
```
dotenvx get TEST
```
#### output
````
onetwo
three
````
#### expected output
```
one
two
three
```

If this is on purpose is there a way to avoid this behavior?

**Comment by motdotla** [comment]
definitely not on purpose. i'll work on reproducing and patching asap.

**Comment by bijeebuss** [comment]
thanks!

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/322

**Comment by motdotla** [comment]
going out as 1.6.5 patch shortly. thank you for catching this.
