### ISSUE TITLE
Add `--exclude-keys` option - allow for excluding certain keys from encryption

### ISSUE THREAD

**Issue by RIP21** [dotenvx/dotenvx#326]
Now there is an option to select those to encrypt using `--keys` flag, but since 80-90% of the keys are sensitive info, it will be nice to have some sort of `--exclude-keys` and only list a bunch of those that are non-sensitive while the rest get encrypted automatically (I specifically have a precommit hook to encrypt).
Having that in a separate file, like some sort of `.dotenvxrc` configuration file, or `JSON` would probably make things even easier.

**Comment by motdotla** [comment]
this is completed here: https://github.com/dotenvx/dotenvx/pull/344

it will go out as part of the 1.9.0 release over the next few days.
