### ISSUE TITLE
possible `tinyexec` issue

### ISSUE THREAD

**Issue by jzila** [dotenvx/dotenvx#329]
I've found the `.env{.foo}`/`DOTENV_PRIVATE_KEY{_FOO}` matching to be extremely brittle and fraught, with no logging when it breaks. This seems to occur due to various issues like Node automatic .env parsing, NextJS automatic .env parsing, and the need to control env var names and filenames in containerized environments.

I propose an explicit Javascript API that allows you to specify the exact private key env var name and env file name, that skips all the matching code. It will always attempt to decrypt using that pair, and will not attempt anything else. Failure to decrypt any `encrypted:` entry will throw an error instead of silently continuing. The `injected:` log entry will also communicate how many entries were decrypted.

This additional API would allow you to also explicitly specify the order of file injection, as well as the override hierarchy.

```javascript
dotenvx.config({
  paths: [
    {
      path: './.my_env_file',
      privateKeyVar: 'MY_DOTENV_PRIVATE_KEY',
      override: true,
    },
  ],
})
```

**Comment by motdotla** [comment]
yes, will consider this strongly. it's been on my mind as well. it needs to have symmetry with the cli though as well.

related: https://github.com/dotenvx/dotenvx/issues/237

**Comment by motdotla** [comment]
related: https://github.com/dotenvx/dotenvx/issues/210

**Comment by motdotla** [comment]
related: https://github.com/dotenvx/dotenvx/issues/316

**Comment by motdotla** [comment]
going to sit on this for a bit as I think the last 3 fixes largely nullify the need for the original request.

1. decryption errors now bubble up to `warn` level logs https://github.com/dotenvx/dotenvx/issues/237 https://github.com/dotenvx/dotenvx/issues/210
2. the javascript `config` api was not properly loading from the `DOTENV_PRIVATE_KEY_${environment}` https://github.com/dotenvx/dotenvx/issues/316

**Comment by jzila** [comment]
I'll try it as soon as the next release is out, thanks!

**Comment by motdotla** [comment]
it's out. `1.10.2` is current latest.

let me know how it goes. still considering the ability to directly pass privateKey as a flag/option, but probably will not prioritize it just yet.

**Comment by jzila** [comment]
It's not picking up the `.env` for me:
```
  @secret=$(set -a; cat .env.keys | eval; set +a; echo "$DOTENV_PRIVATE_KEY_LOCAL"); podman run --rm --env-file .env.local --env DEBUG=true --env DOTENV_PRIVATE_KEY="$secret" --network=host inkbloom-{{image}}
```
The start script saves an allow-list of variables into `.env` and then relies on `DOTENV_PRIVATE_KEY`.
When I use this instead, it works:
```
HOSTNAME="0.0.0.0" bunx @dotenvx/dotenvx@1.7.0 run --overload -f "$VAULT_FILE" -- bun run ./dist/server.js &
```

Note: 1.9.*, 1.10.*, 1.11.* builds fail to execute in `bun` at all:
```
[dotenvx@1.11.3] injecting env (12) from ./.env
undefined is not a function (near '...o of this._streamErr...')
```

vs
```
[dotenvx@1.7.0] injecting env (12) from ./.env
```

**Comment by motdotla** [comment]
it looks like dotenvx succeeded:

```
[dotenvx@1.11.3] injecting env (12) from ./.env
```

but that maybe your code is failing? 

```
undefined is not a function (near '...o of this._streamErr...')
```

that doesn't look dotenvx related.

if you instead run: `HOSTNAME="0.0.0.0" bunx @dotenvx/dotenvx@1.7.0 get --pretty-print` does that output the correct environment variables?

**Comment by motdotla** [comment]
oops, also make sure that is using `1.11.3` rather than 1.7.0 as you currently have it.

**Comment by motdotla** [comment]
also i would guess that `bunx some-npm-module` probably won't work with bun's runtime. deno's is incompletely implemented currently for these ciphers and bun probably is too, being so young:

https://github.com/dotenvx/dotenvx/issues/353

i would recommend install dotenvx as a binary and using it that way. less that can go wrong.

**Comment by jzila** [comment]
OK here are the results:
```
# works
bunx @dotenvx/dotenvx@1.11.3 get --overload -f "$VAULT_FILE" --pretty-print

# outputs the decrypted `env` followed by the undefined is not a function error
bunx @dotenvx/dotenvx@1.11.3 run --overload -f "$VAULT_FILE" -- env

# injects the env but then fails with the undefined is not a function error
HOSTNAME="0.0.0.0" bunx @dotenvx/dotenvx run --overload -f "$VAULT_FILE" -- bun run ./dist/server.js &
```

**Comment by jzila** [comment]
`bunx` uses the node runtime by default unless you pass in `--bun` FWIW

**Comment by jzila** [comment]
When I do all of the above with `dotenvx@1.7.0`, everything works.

**Comment by motdotla** [comment]
yeah, does look like bunx works. nice!

```
echo "HELLO=world" > .env
bunx @dotenvx/dotenvx@1.11.3 encrypt
bunx @dotenvx/dotenvx@1.11.3 get
bunx @dotenvx/dotenvx@1.11.3 env
```

trying your scenarios. this is likely going to be a command line parsing issue i think - for how flags are being read

**Comment by motdotla** [comment]
```
echo "HELLO=production" > .env.production
bunx @dotenvx/dotenvx@1.11.3 encrypt -f .env.production
bunx @dotenvx/dotenvx@1.11.3 get -f .env.production
bunx @dotenvx/dotenvx@1.11.3 run -f .env.production -- env
```

^ this all works correctly for me locally

**Comment by motdotla** [comment]
```
$ bunx --version
1.1.8
```

**Comment by motdotla** [comment]
```
# outputs the decrypted `env` followed by the undefined is not a function error
bunx @dotenvx/dotenvx@1.11.3 run --overload -f "$VAULT_FILE" -- env
```

what's this look like if you add --debug flag

```
bunx @dotenvx/dotenvx@1.11.3 run --overload -f "$VAULT_FILE" --debug -- env
```

can you print the entire output but with things redacted? so i can see the undefined is not a function error as well. doesn't sound like that is coming from dotenvx.

**Comment by motdotla** [comment]
also what kind of KEYS in the file you are loading? maybe there is some weird self-referential thing going on that is very edge case and hasn't been accounted for in the code.

**Comment by jzila** [comment]
> what's this look like if you add --debug flag

```
Setting log level to debug                                                                        
process command [env]                                                                             
options: {"env":[],"envFile":["./.env"],"envVaultFile":[],"overload":true}                        
loading env from ./.env (/home/bun/app/.env)     
{"ENV_MODE":"dev", ...<other decrypted values>}
ENV_MODE set                                                                                                                                                                                        
ENV_MODE set to dev                                                                                                                                                                                 
...<other decrypted values>
[dotenvx@1.11.3] injecting env (12) from ./.env
executing process command [env]                                                                   
expanding process command to [/usr/bin/env]
...<decrypted env>
```

>  also what kind of KEYS in the file you are loading? maybe there is some weird self-referential thing going on that is very edge case and hasn't been accounted for in the code.

These are all `FOO="encrypted:<base64>"`

```
venator:/home/bun/app# cat .env
ENV_MODE="encrypted:BO9ixHlgqLCv6...=="
```

**Comment by motdotla** [comment]
```
Setting log level to debug                                                                        
process command [env]                                                                             
options: {"env":[],"envFile":["./.env"],"envVaultFile":[],"overload":true}                        
loading env from ./.env (/home/bun/app/.env)     
{"ENV_MODE":"dev", ...<other decrypted values>}
ENV_MODE set                                                                                                                                                                                        
ENV_MODE set to dev                                                                                                                                                                                 
...<other decrypted values>
[dotenvx@1.11.3] injecting env (12) from ./.env
executing process command [env]                                                                   
expanding process command to [/usr/bin/env]
...<decrypted env>
```

looks like that worked then? i don't see the error you were describing happened when running `-- env`

i think this is in your code that follows the `--`. i'm going to close.

**Comment by jzila** [comment]
Edited to include the `undefined` error

**Comment by jzila** [comment]
I thought you reproduced it with `env`...

**Comment by jzila** [comment]
> so i can see the undefined is not a function error as well. 

It happens on 1.11.3, but doesn't happen on 1.7.0. Seems like it must be from dotenvx.

**Comment by motdotla** [comment]
> I thought you reproduced it with bunx @dotenv/dotenvx run --overload -- env

no, i cannot reproduce this at all.

https://github.com/user-attachments/assets/ff940b71-b543-460d-b2aa-ed9d97dfe1f2

if you run the `env` command by itself do you get the same error?

```
$ env
```

if you run `dotenvx-cli` do you get the same error?

```
$ bunx dotenv-cli -- env
```

what bun version are you on?

**Comment by jzila** [comment]
`dotenv-cli` doesn't have the same error, but it also doesn't decrypt.

```
bun/1.1.25 npm/? node/v22.6.0 linux x64
```

The error reproduces with 1.1.20 as well, though.

**Comment by motdotla** [comment]
> but it also doesn't decrypt.

dotenv-cli is a totally different cli. it doesn't encrypt or decrypt at all.

> `dotenv-cli` doesn't have the same error

wait, so does it have a different error? or no error at all?

please be more verbose and clear. i need more information to help you debug.

what os are you on?

**Comment by jzila** [comment]
`dotenvx-cli` has no error, apologies for the lack of clarity.

The issue is happening on a container that inherits from `FROM oven/bun:1.1.25-alpine`, and it appears to happen even in a naked container:

```
➜ podman run -it --rm --entrypoint=/bin/sh oven/bun:1.1.25-alpine 
/home/bun/app # bunx @dotenvx/dotenvx run --overload -- env
[dotenvx@1.11.3] missing .env file (/home/bun/app/.env)
? add one with [echo "HELLO=World" > .env] and re-run [dotenvx run -- env]
[dotenvx@1.11.3] injecting env (0)
BUN_INSTALL_BIN=/usr/local/bin
HOSTNAME=d9f21b21a0b5
SHLVL=1
HOME=/root
container=podman
TERM=xterm
PATH=/tmp/bunx-0-@dotenvx/dotenvx@latest/node_modules/.bin:/tmp/bun-node-fe62a6140:/home/bun/app/node_modules/.bin:/home/bun/app/node_modules/.bin:/home/bun/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/bun/app/node_modules/.bin:/home/bun/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin
PWD=/home/bun/app
BUN_RUNTIME_TRANSPILER_CACHE_PATH=0
npm_config_local_prefix=/home/bun/app/
npm_config_user_agent=bun/1.1.25 npm/? node/v22.6.0 linux x64
npm_execpath=/usr/local/bin/bun
NODE=/tmp/bun-node-fe62a6140
npm_node_execpath=/tmp/bun-node-fe62a6140
BUN_INTERNAL_BUNX_INSTALL=true
undefined is not a function (near '...o of this._streamErr...')
```

**Comment by motdotla** [comment]
ok, thank you, i will try there and see if i can reproduce.

**Comment by motdotla** [comment]
can you share your Dockerfile contents actually? just redact anything sensitive.

**Comment by motdotla** [comment]
one of the few references to `this._streamErr` happens to be `tinyexec` - which we switched to after `1.7.0`

https://github.com/search?q=%22this._streamErr%22&type=code
https://github.com/dotenvx/dotenvx/blob/main/CHANGELOG.md#changed-7

**Comment by jzila** [comment]
Nice find! That's consistent with my observations that `1.8.0` reproduces this issue, but `1.7.0` does not.

Do you still need the detailed Containerfile?

**Comment by motdotla** [comment]
yes i do

**Comment by motdotla** [comment]
> yes i do

actually, nevermind. i'm able to reproduce now!

this was a frustrating one! sorry i thought it was your code. patching up now and will add a test to our ci to catch these in the future.

**Comment by jzila** [comment]
Believe me, I get it. Thanks for your responsiveness and collaboration!

**Comment by motdotla** [comment]
failing test: https://github.com/dotenvx/dotenvx/actions/runs/10603238006/job/29387091055?pr=361

**Comment by motdotla** [comment]
ok, `1.11.5` fixes the problem.

**Comment by motdotla** [comment]
@SuperchupuDev i had to revert tinyexec. it outputs error text if used with `bunx`:

https://github.com/dotenvx/dotenvx/actions/runs/10603969932/job/29389794695

<img width="625" alt="image" src="https://github.com/user-attachments/assets/80903a89-4bbe-45ce-8cc5-24b23c152ea2">

maybe you can look into it, if you get a chance, and we can bring back tinyexec. i chose to just revert to get the fix out fast for anyone this is affecting.

**Comment by SuperchupuDev** [comment]
thanks for telling me, i've forwarded this issue to the tinyexec maintainer. i believe this should also be reported in bun as they want to achieve full node compatibility

**Comment by SuperchupuDev** [comment]
@motdotla what's the full stack trace of the error?

**Comment by motdotla** [comment]
that's all we had. was strange. like an error was becoming a string and then outputting.
