### ISSUE TITLE
helpers/packageJson makes dotenvx un-bundleable

### ISSUE THREAD

**Issue by jzila** [dotenvx/dotenvx#330]
Some bundlers attempt to build a standalone version of imported libraries. As such, a bundler mostly traces source code alone, plus imported assets. Files that are dynamically loaded by a library are typically not traced by bundlers.

Dotenvx loads `package.json` dynamically in `lib/helpers/packageJson.js`. NextJS's bundling tracer is smart enough to handle this, but Bun's isn't, and I suspect there are others.

The simplest solution would be to instead `import` the file or `require` it instead of loading it with `JSON.parse(fs.readFileSync(...))`, which would allow bundlers to load it. However, removing the dependency would likely be better. You could do so with https://docs.npmjs.com/cli/v6/using-npm/scripts#packagejson-vars

**Comment by motdotla** [comment]
isn't this something bun should fix?

i'd prefer not to rely on npm infrastructure. this should be available to anyone running from source.

**Comment by jzila** [comment]
That's fair. Then maybe the `require` solution would be appropriate.

**Comment by jzila** [comment]
I am curious, though - the `packageJson.js` file is depending on `npm` conventions for obtaining `name`, `version`, and `description`. What's the packaging/bundling strategy if not `npm`?

**Comment by jzila** [comment]
Re: hoping for `bun` to fix this, I'd say that is somewhat challenging to expect. The `dotenvx` library package is effectively depending on a dynamically-loaded file whose existence in the dependency graph can only be determined by executing the code. Most bundlers/packagers don't execute the code, instead relying on static analysis through `require`/`import` statements \[1]. I wouldn't expect any bundler to discover the dependency on a file read through `fs.readfile` pointed to by a variable.

\[1]: https://survivejs.com/books/webpack/introduction/#how-webpack-changes-the-situation

**Comment by motdotla** [comment]
> I am curious, though - the packageJson.js helper is depending on npm conventions for obtaining name, version, and description. What's the packaging/bundling strategy if not npm?

it's not depending on npm here. it's just depending on a json file. that json file happens to have good mechanisms for bumping versions - so using version there avoids the headache of maintaining a version constant elsewhere in the code.

**Comment by motdotla** [comment]
> depending on a dynamically-loaded file whose existence in the dependency graph can only be determined by executing the code

it's very common for code to read from a file - especially a json file it wants to parse. the file lives in the npm package tarball. not sure why bun wouldn't treat that as part of its static analysis process. 

that said, i'd rather get this working for bun users earlier than later. i'll do some testing on your pr that uses require. i vaguely remember edge case problems with that though.
