### ISSUE TITLE
[BUG] encrypt/decrypt work not correct on `.env.production` specially

### ISSUE THREAD

**Issue by slow-groovin** [dotenvx/dotenvx#332]
# environment
win10,  powershell,  dotenvx: v1.7.0
# problem
## description
When use name `.env.prodution` , it will not be  decrypted.  use other any name (`.env.any`) will be ok.

## encrypt
```
dotenvx encrypt -f .\.env.production
```
## decrypt, will not work
```
dotenvx decrypt -f .\.env.production  
```
## run, will not work
```
 dotenvx.cmd  run -f .env.production -- node index.js

```

index.js
```
console.log("HELLO",process.env.HELLO)

```

output:
```
[dotenvx@1.7.0] injecting env (2) from .env.production
HELLO encrypted:BBpc1Kaos/C**********=

```

**Comment by slow-groovin** [comment]
I have test many  times later,  and not make a reproduction. I notice that encrypt/decrypt has a  obvious lag. I guess maybe the lag cause some bug in previous tests.

**Comment by motdotla** [comment]
i can't reproduce this either. typically this means your .env.keys was malformed or missing. maybe you moved the location of your `.env.production` file but did not move your `.env.keys` file.

**Comment by motdotla** [comment]
@b-bot if you replace what with `test`, it works? i've just tested this and i see the following occuring:

i've tried reproducing with the following set up:

```json
{
  "scripts": {
    "dotenvx": "dotenvx"
  },
  "dependencies": {
    "@dotenvx/dotenvx": "^1.8.0"
  }
}
```

```
npm run dotenvx -- set HELLO production -f .env.production
```

i cannot reproduce what you are experiencing. it correctly warns me to first create the `.env.production` file.

https://github.com/user-attachments/assets/1b7e11d3-5923-47b1-965d-e8d0a47fb7ef

is there something different with your setup here?

**Comment by motdotla** [comment]
@b-bot do you happen to be running your command without the `--`?

```
$ npm run dotenvx set HELLO production -f .env.production
```

The arguments provided after the script name are processed by npm itself - essentially stripping the -f option away from dotenvx. As a result, dotenvx will run as if there is now file option -  `dotenvx set HELLO production` - thereby defaulting to write to `.env`.

Is this what you are seeing?
