### ISSUE TITLE
dotenvx precommit hook should check subfolders

### ISSUE THREAD

**Issue by MykalMachon** [dotenvx/dotenvx#333]
## Problem
The pre-commit hook does not catch .env.* variables outside of the root folder. For example, the commit hook, as it is currently, will throw for: 
- `/.env`
- `/.env.production`

However, it does _not_ catch for any `.env` file _not_ located in the repositories root directory. For example: 

- `/packages/api/.env` or `packages/api/.env.production`

## Expected Behavior

I would expect the pre-commit hook to find and error out on _any_ .env file in a repository that is not encrypted including those in subfolders. 

I work on multiple "monorepo" style repositories that contain multiple applications under a `packages` or `services` folder 
(i.e. `packages/api` `packages/web` `packages/core`) and as is the pre-commit hook simply will not work with that setup.  

## Solution 

This could be resolved [by updating the pre-commit hook code here](https://github.com/dotenvx/dotenvx/blob/3d090dec1bbed79ff064c64d8948546a3b72042e/src/lib/services/precommit.js#L41) to recurse through all folders in the repo when looking for `.env` files.

**I'd be happy to submit a PR for this if you'd like!** not sure what the contributing guidelines on here but if you're open to contributors just assign this issue to me and I'll get to work 😄

**Comment by BenJackGill** [comment]
+1 I just ran into this same issue

**Comment by motdotla** [comment]
@MykalMachon good catch. yes, can you submit a PR. that would be really great for the project and the community.

**Comment by MykalMachon** [comment]
@motdotla thanks for the suggestion! 
I just started writing an implementation with `fs.readDirSync()` directly but I'd rather re-use some logic defined elsewhere in the application to keep logic consistent. This also looks like it'll also be easier to mock and test.

**Comment by motdotla** [comment]
oh, also `lib/services/ls.js` could be helpful as well. `lib/services/status.js` puts it to use.

**Comment by motdotla** [comment]
released as `1.10.1`

**Comment by motdotla** [comment]
hmm @MykalMachon, maybe we went too far:

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/1acb925d-60e4-4c25-b9f3-65eb851de0d0">

now i can't commit to dotenvx with its own precommit 🤣

because tests/**/.env*

**Comment by MykalMachon** [comment]
Oh shoot! 
Maybe add an exception to the test path? 

Or maybe a way to add path exceptions to the precommit hook as an option when installing it 🤔

**Comment by MykalMachon** [comment]
Hey @motdotla, 
I did some cursory digging around in the codebase, and I think adding an option to add an `--ignore-paths` flag would be pretty simple to implement! here's what I'm thinking. 

0. write a test to validate that when `--ignore-paths some/path/**` is passed in to the precommit hook it doesn't throw for files in that folder. 
     * Ideally ignore paths could also handle a comma separated list of regex patterns to test against (i.e. `--ignore-paths some/**,path/**,here/**/*` so I'll include a test case for that as well. 
2. Alter the [pre-commit extension CLI command](https://github.com/dotenvx/dotenvx/blob/a4ef856318f44af5e713fbe1202a5ff4f4591e8b/src/cli/commands/ext.js#L50-L54) and [the constructor for the precommit service class](https://github.com/dotenvx/dotenvx/blob/a4ef856318f44af5e713fbe1202a5ff4f4591e8b/src/lib/services/precommit.js#L13-L15) to add the new option. 
3. add an option into [the constructor for the `installPrecommitHook` class called "options"](https://github.com/dotenvx/dotenvx/blob/a4ef856318f44af5e713fbe1202a5ff4f4591e8b/src/lib/helpers/installPrecommitHook.js#L17-L19) or something similar that would let you pass in the install options. 
4. alter the installPrecommitHook class to append any options to the last bit of HOOK_SCRIPT in the correct format. [This may involve refactoring HOOK_SCRIPT to be a function that takes in the options and returns a string](https://github.com/dotenvx/dotenvx/blob/a4ef856318f44af5e713fbe1202a5ff4f4591e8b/src/lib/helpers/installPrecommitHook.js#L4-L14) (`generateHookScript(options)`).
5. alter the precommit service class to support the `--ignore-paths` option which would [filter the results of the Ls Service run](https://github.com/dotenvx/dotenvx/blob/a4ef856318f44af5e713fbe1202a5ff4f4591e8b/src/lib/services/precommit.js#L44) to not include any file path strings that match the regex patterns handed in by `--ignore-paths`. 
6. Ensure tests are passing 
7. Run a format on it all! 

**If you want, I can take a shot at this in the next while!** I'm in the middle of moving house right now so it might be a week or so until I have time to take a crack at it. Let me know!

**Comment by motdotla** [comment]
yes, i largely agree. though right now i want to have the default be hardcoded on precommit.

* `ls` will get a `--exclude-env-file (-ef)` flag/argument
* `precommit` will make use of that flag/argument to hardcode a list of typical test folders to ignore

**Comment by motdotla** [comment]
going out as `1.11.0` https://github.com/dotenvx/dotenvx/pull/356
