### ISSUE TITLE
color support detector is wrong

### ISSUE THREAD

**Issue by SuperchupuDev** [dotenvx/dotenvx#341]
got confused and used the wrong numbers in getColorDepth(), to fix replace `2` with `1`, `16` with `4` and `256` with `8`. see https://nodejs.org/api/tty.html#writestreamgetcolordepthenv

**Comment by SuperchupuDev** [comment]
i'm pretty sure 8a869f4aa793663b1a7848911a3382738a17cbf5 won't be necessary after fixing this, 8bit colors is just ansi256

**Comment by motdotla** [comment]
ok nice. go ahead and remove then. i can test on my machine after.

**Comment by motdotla** [comment]
the colordepth on my machine/terminal is 8 when i console.log out that check

**Comment by SuperchupuDev** [comment]
yes exactly, i had assumed the check would return 256 for 8bit colors but instead it returns 8, the getColor related functions need to get updated

**Comment by motdotla** [comment]
working great now
