### ISSUE TITLE
Treat encrypted envrionment vars as empty if key is not provided

### ISSUE THREAD

**Issue by pksunkara** [dotenvx/dotenvx#358]
Currently, when a key is not provided but an env var is encrypted, using `dotenvx` provides the encrypted value as the value directly which might lead to false assumptions of the key being present in the code.

A better experience would be to make the encrypted env var value to be `''` and thus reflecting the actual situation that this specific env var has not been provided.

**Comment by motdotla** [comment]
i disagree. encrypted is not equal to '' and decrypted is not equal to ''. instead we warn.

Are you getting the warning in your logs on `dotenvx run` ?

**Comment by motdotla** [comment]
i should add, i currently disagree. i don't hold strongly to this yet. i've considered the cli exiting, but that has never been the spirit of dotenv. it's always loaded even if you were missing keys, etc.

**Comment by pksunkara** [comment]
Yeah, I am getting the warning. And you have the right to disagree and close this issue. And I was never talking about CLI failing. IMHO, the cli should just process them to be `''`.

In my code, I found that it's much easier to treat non-decrypted values as empty and fail differently. For example:

```ts
import { init } from '@sentry/node';

init({
  dsn: process.env.SENTRY_DSN,
});
```

I have the above code. Having a non-decrypted value (because of the key missing) would make sentry look like it's working until an error happens.

But if the CLI sets it to `''`, then this function call would fail when starting the server and thus increases the awareness of the key being missing.

Also, I find that this is a better way of providing optional env vars and sharing the .env file along with the code.

**Comment by motdotla** [comment]
could you modify your function call to check if a string starts with `encrypted:` instead of checking for empty string?

**Comment by motdotla** [comment]
or if dotenvx provided something like a --fail flag/option would that remove your need for that code you use to check for empty strings?

**Comment by pksunkara** [comment]
> could you modify your function call to check if a string starts with encrypted: instead of checking for empty string?

That is the workaround I currently have.

> or if dotenvx provided something like a --fail flag/option would that remove your need for that code you use to check for empty strings?

I don't think fail would work since that wouldn't handle the scenario of having optional env vars especially in the case of open source projects.

**Comment by pksunkara** [comment]
To illustrate further in those optional env var situations, the above-mentioned code example would change to:

```ts
import { init } from '@sentry/node';

if (!!process.env.SENTRY_DSN) {
  init({
    dsn: process.env.SENTRY_DSN,
  });
}
```

Currently, the workaround is `if (!process.env.SENTRY_DSN.starts_with('ecrypted:')) {

**Comment by motdotla** [comment]
ok, i think that is reasonable though - especially since this is custom logic you are implementing anyways.

there is a large benefit to keeping the `encrypted:` as well on failure to encrypt. it communicates to the user it failed to decrypt. otherwise, we could waste a lot of dev hours for people around the world when they wonder why it is blank - like 'did i set it right? is it being called? did it load the encrypted file?'. there are way more questions to ask then 'oh, looks like decryption failed, let me look into why'
