### ISSUE TITLE
Don't generate .env.keys if I have DOTENV_PRIVATE_KEY set in env

### ISSUE THREAD

**Issue by charlie0077** [dotenvx/dotenvx#365]
I have DOTENV_PRIVATE_KEY set in my system environment, i.e. i don't want to have a .env.keys file. 

However when I run dotenv set HELLO value, it will generate an empty .env.keys file, which is annoying.

**Comment by charlie0077** [comment]
Basically no empty .env.keys file

**Comment by motdotla** [comment]
starting to work toward this here: https://github.com/dotenvx/dotenvx/pull/401

**Comment by motdotla** [comment]
going out as `v1.20.0`. give it a go and let me know if you run into any issues.
