### ISSUE TITLE
Cannot run project package.json scripts in JS monorepo

### ISSUE THREAD

**Issue by tsi-trmorris** [dotenvx/dotenvx#371]
I'm having issues with running `dotenvx` from a `package.json` script in JS monorepo (pnpm + nx). 
I've created the following script in my `package.json`:

```json
{
  "scripts": {
    "dev": "dotenvx run -f .env.local -f .env -- nuxi dev"
  }
}
```

To start my dev script normally, I run `pnpm -- nx dev <my_proj>`

The script above produces this output:
```
> nx run <my_proj>:dev

> <my-proj>@1.0.0 dev <path-to-proj>
> dotenvx run -f .env.local -f .env -- nuxi dev
[dotenvx@1.13.2] missing nuxi file (<path-to-proj>\nuxi)
? add one with [echo "HELLO=World" > nuxi] and re-run [dotenvx run -- ]
[dotenvx@1.13.2] missing dev file (<path-to-proj>\dev)
? add one with [echo "HELLO=World" > dev] and re-run [dotenvx run -- ]
[dotenvx@1.13.2] injecting env (0) from .env.local, .env
missing command after [dotenvx run --]

  get help: [dotenvx help run]
  or try:   [dotenvx run -- npm run dev]
 ELIFECYCLE  Command failed with exit code 1.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Running target dev for project <my_proj> failed

   Failed tasks:

   - <my_proj>:dev

   Hint: run the command with --verbose for more details.
```

Limiting to only one `.env` file yields the same result.

I did find a way to run successfully using `pnpx @dotenvx/dotenvx run -f .env.local -f .env -- nuxi dev`, but this certainly feels less than ideal.

System info:
```
OS: Windows 11 22H2 (22621.4037)
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
```

**Comment by tsi-trmorris** [comment]
https://github.com/tsi-trmorris/dotenvx-issue-371
Hopefully this should be a solid enough repro for this. I've decided to remove the `nuxi` cli calls from the rats nest since the issue persists for me even when running a simple js file with node.

My team and I run our scripts as `pnpm -- ...` so we are able to call a specific script of a specific package from the root of our monorepo without navigating to that package. I'm sure there's another (likely easier) way to accomplish this, but that's how we interact with our frontend monorepo.

**Comment by motdotla** [comment]
ok thanks. might end up related to how dotenvx works with pnpm then. 

appreciate this! i'll try and debug soon.

**Comment by motdotla** [comment]
here's currently what i receive back:

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/5dbf56f3-058b-4f9a-98ae-69bd0dec30dd">

**Comment by motdotla** [comment]
where is your dotenvx installed? `which dotenvx`

**Comment by motdotla** [comment]
if i uninstall my local dotenvx - and use the one in your package.json file - it also appears to work successfully:

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/b8aea217-de89-4a46-90d3-a5cf5ce4215b">

I'm receiving back `fizzbuzz buzz` - in both cases.

**Comment by motdotla** [comment]
my pnpm and node versions:

<img width="588" alt="image" src="https://github.com/user-attachments/assets/ef06fa66-2964-4f3c-bf50-1c8315922755">

**Comment by motdotla** [comment]
![Capture](https://github.com/user-attachments/assets/7e0bb833-9b8d-4597-9053-f688c5b86aa1)

also works well on windows.

i'm going to mark this closed as this does not appear to be a dotenvx issue.

please let me know though when you see this and still see a problem and i will re-open as needed.

**Comment by tsi-trmorris** [comment]
Interesting. Thanks for taking a look.

**Comment by motdotla** [comment]
maybe there is an older and bad version of dotenvx installed somehow on your machine? do you have a teammate or friend that can also test to see what might be the issue?
