### ISSUE TITLE
Decrypt: Exit with non-zero exit code on failure

### ISSUE THREAD

**Issue by benjaminbauer** [dotenvx/dotenvx#373]
When I run `dotenvx decrypt -f .env.somefile` without the proper keys available, I get `private key missing or blank` and an exit code of `0`.

My expectation: Exit code is not 0.

Why is this relevant: When used in a script, a non-zero exit code is the best way to detect if a comman worked or not.

**Comment by motdotla** [comment]
agree. will patch up.

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/374

going out shortly as `1.13.3`
