### ISSUE TITLE
dotenvx decrypt does not escape double quotes

### ISSUE THREAD

**Issue by pibica** [dotenvx/dotenvx#377]
let start with plain env variable that contains a stringified object:
`obj={"test":1}`

do `dotenvx encrypt`
-> `obj="encrypted:BAjM9+QxMeiOIic...nSjm60Uswjt02LhQev5rRDzY="`

do `dotenvx decrypt`
-> `obj="{"test":1}"` ***double quotes are not escaped***

do `dotenvx encrypt`
-> `obj="encrypted:BDQ/8baLJ8/zj9/o5fruLrr/...lTA8="test":1}"`
which is incorrect

proposal: 
when doing `dotenvx decrypt`:
 if the variable contains double quotes, but no backticks \` (0x60) then enclose the value with backticks, no need to escape double quotes (this way, the result is more human readable).
 if the variable contains double quote, and backticks \` then enclose the value with double quotes and escape double quotes

**Comment by motdotla** [comment]
good catch. will work on patching up.

**Comment by motdotla** [comment]
this goes a little deeper - with some other edge cases issues around encrypting/decrypting non-escaped quotes (and other characters). needs a smarter `replace`. effort happening here: https://github.com/dotenvx/dotenvx/pull/395/files

**Comment by motdotla** [comment]
this is fixed in `v1.18.0`. thank you for reporting.

**Comment by motdotla** [comment]
update: this is now handled in a more intuitive way - by respecting the user's chosen quotes.

https://github.com/dotenvx/dotenvx/pull/423

going out as 1.21.0
