### ISSUE TITLE
I have env files but still showing this -> [dotenvx@1.14.0] {"code":"MISSING_ENV_FILE"} 

### ISSUE THREAD

**Issue by shubhamGhosh-dev** [dotenvx/dotenvx#379]
Hi, i am trying to use different environment file on my project using dotenvx, but getting unexpected warning.

I have 2 environment files following ->
```
   .env.production
   .env.development
```

package.json -> 
```
    "start": "dotenvx run -f .env.production -- node dist/index.js",
    "dev": "dotenvx run -f .env.development -- nodemon src/index.ts",
```

Node.js version -> `v20.12.2`

The warning i am getting ->

![Screenshot 2024-09-10 133412](https://github.com/user-attachments/assets/0678aced-c35a-49dc-a311-d19d8740c846)

thanks!

**Comment by motdotla** [comment]
you must have dotenvx loaded twice somehow. that second call is looking for a `.env` file instead of a `.env.development` file.

I see you have it in your start scripts:

```
"start": "dotenvx run -f .env.production -- node dist/index.js",
```

are you also `require('@dotenvx/dotenvx')`-ing it somewhere in your code?

**Comment by motdotla** [comment]
it looks like it must be this because the second injection log happens after you run tsc. going to close this and will reopen if something else. let me know.
