### ISSUE TITLE
Support regex in --exclude-key

### ISSUE THREAD

**Issue by alaychak-hc** [dotenvx/dotenvx#381]
I sometimes will encrypt and decrypt my env files as a whole and for my Next JS application, there are some public values that are okay with being public. The issue is that I can't fully encrypt the file due to how Next JS doesn't decrypt them properly. 

Is it possible to support regex for encrypt / decrypt? I know --ek works, but I would prefer to do it all in one go and not have to list all the values individually. #344 is the one that supported -ek, but doesn't seem to support regex. I would like to be able to do "dotenvx encrypt -ek NEXT_PUBLIC_*" and have it exclude all public values in my env file, but encrypt the rest. 

This would also benefit other libraries that use other prefixes (https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#framework-inference)

Thanks for the wonderful library.

**Comment by motdotla** [comment]
this was added to `1.19.0`. enjoy 🎉

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/7c260940-a82b-4161-bf8b-78b9e68ef14c">
