### ISSUE TITLE
Unable to Access Environment Variables in Angular after Injection using dotenvx

### ISSUE THREAD

**Issue by MAVRICK-1** [dotenvx/dotenvx#384]
### Issue Description:

<img width="959" alt="Screenshot 2024-09-20 102034" src="https://github.com/user-attachments/assets/4d5678dc-e3b3-410b-9c7a-fce44d70c051">

Hello,

I am facing an issue while trying to access environment variables in my Angular project using **dotenvx**. I am able to successfully inject the environment variables, but for some reason, I cannot access them within my components or services.

Here’s a brief description of what I've done:

1. Installed dotenvx in my Angular project.
2. Created a `.env` file at the root of my project with the necessary variables.
3. Injected the environment variables into the Angular application using dotenvx as per the documentation.

I can see that the variables are being injected, but when I try to access them in the code (for example, `process.env['MY_VARIABLE']`), I get undefined values. I have also tried to log the variables, but they don’t seem to be available in the application context.

I’ve double-checked that the variables are properly injected, and they do exist in the `.env` file.

I would appreciate any guidance on how to resolve this issue or if there is something I am missing when using **dotenvx** with Angular.

Thank you!
@motdotla

**Comment by motdotla** [comment]
i think this is a default limitation of angular. angular doesn't support process.env if i remember right? isn't there an angular plugin to add support for it or something?

**Comment by motdotla** [comment]
closing this as i believe this is an angular limitation.
