### ISSUE TITLE
Does not forward process kill signal to Node.js application

### ISSUE THREAD

**Issue by niklasschloegel** [dotenvx/dotenvx#385]
I have a Node.js application which I run with the following start script

```json
{
  ...,
  "scripts": {
    "start": "dotenvx run --env-file=.env -- node ./dist/app/index.js"
  },
  ...
}
```

This application registers a callback on receiving a kill signal with

```js
process.once(signal, handleSignal)
```

When now running the `start` script from above and hit ^C in the process terminal, the callback does not get called. Before that I had the old dotenv version with programmatic initalization of the env-file and a simple start script that just executed `node ./dist/app/index.js`, where the callback got called.

I expect that the signal gets forwarded even when using `dotenvx run`. Is there a way around that, or is this an actual issue?

**Comment by motdotla** [comment]
at first glance everything looks to be in order. here's an attempt at reproducing the issue with no luck:

first, the setup:

```bash
mkdir app1
cd app1
echo "HELLO=World" > .env
npm install @dotenvx/dotenvx --save
```

```js
// index.js
const handleSignal = (signal) => {
  process.stdout.write('Received SIGINT, shutting down gracefully...\n', () => {
    process.exit(0)
  })
}

process.once('SIGINT', () => handleSignal('SIGINT'))

console.log(`HELLO: ${process.env.HELLO}. Press Ctrl+C to exit.`)

setInterval(() => {
  console.log('Working...')
}, 1000)
```

```json
{
  "scripts": {
    "start": "dotenvx run -- node index.js"
  },
  "dependencies": {
    "@dotenvx/dotenvx": "^1.14.1"
  }
}
```

second, the runs:

*node index.js*

```bash
➜  app1 node index.js
HELLO: undefined. Press Ctrl+C to exit.
Working...
Working...
Working...
^CReceived SIGINT, shutting down gracefully...
```

*dotenvx run -- node index.js*

```bash
➜  app1 dotenvx run -- node index.js
[dotenvx@1.14.1] injecting env (1) from .env
HELLO: World. Press Ctrl+C to exit.
Working...
Working...
Working...
^CReceived SIGINT, shutting down gracefully...
```

*npm start*

```bash
➜  app1 npm start

> start
> dotenvx run -- node index.js

[dotenvx@1.14.1] injecting env (1) from .env
HELLO: World. Press Ctrl+C to exit.
Working...
Working...
^CReceived SIGINT, shutting down gracefully...
```

*npm run start*

```bash
➜  app1 npm run start

> start
> dotenvx run -- node index.js

[dotenvx@1.14.1] injecting env (1) from .env
HELLO: World. Press Ctrl+C to exit.
Working...
Working...
Working...
^CReceived SIGINT, shutting down gracefully...
```

signal handling happens around here: https://github.com/dotenvx/dotenvx/blob/d97902b22b69c978e80b66a5757011cebb007c71/src/lib/helpers/executeCommand.js#L16

if you add the `--debug` flag to your dotenvx run code, what output do you get?

**Comment by motdotla** [comment]
closing this as everything seems in order but i will reopen if you find different. maybe you can share more info on what server you are using.
