### ISSUE TITLE
Unexpected error message printed on exit

### ISSUE THREAD

**Issue by nfantone** [dotenvx/dotenvx#394]
`dotenvx run` prints an exit message when my application terminates with an exit code different than `0`, even if setting `--quiet`.

```sh
$ dotenvx run --quiet -f .env.local -- node app.js

^C[12:59:11.602] WARN (my.service): SIGINT received: shutting down
Command exited with exit code 1: /private/var/folders/lh/jz6l0mjd2z10k001hrmnlnr40000gp/T/xfs-e6874183/node app.js

echo $?
139
```

This seems to come from [this line](https://github.com/dotenvx/dotenvx/blob/fb2acb73252186a3b075a50c2dd14a184fbff39e/src/lib/helpers/executeCommand.js#L101). It also looks like [using `--quiet` sets the log level to `'error'`](https://github.com/dotenvx/dotenvx/blob/fb2acb73252186a3b075a50c2dd14a184fbff39e/src/shared/logger.js#L147), which makes it impossible to suppress.

Ideally, I would like to avoid this since it's not only unnecessary and noisy but also misleading. It's certainly not an error and it seems to print an exit code which doesn't match the actual code the process ended with, as shown above.

Maybe having a `--silent` flag would help?

**Comment by nfantone** [comment]
For now, I've created the following patch with `yarn patch`, which changes the log level for those command messages to `debug`.


```diff
diff --git a/src/lib/helpers/executeCommand.js b/src/lib/helpers/executeCommand.js
index 02f6698b13c462dd1a70396d24dab4a120ca6114..2b95cde8d4f9d41816e54e834d730c640691fde3 100644
--- a/src/lib/helpers/executeCommand.js
+++ b/src/lib/helpers/executeCommand.js
@@ -98,9 +98,9 @@ async function executeCommand (commandArgs, env) {
       if (error.code === 'ENOENT') {
         logger.errornocolor(`Unknown command: ${error.command}`)
       } else if (error.message.includes('Command failed with exit code 1')) {
-        logger.errornocolor(`Command exited with exit code 1: ${error.command}`)
+        logger.debug(`Command exited with exit code 1: ${error.command}`)
       } else {
-        logger.errornocolor(error.message)
+        logger.debug(error.message)
       }
     }
```

**Comment by motdotla** [comment]
I can't reproduce this. dotenvx is already built to gracefully handle `SIGINT` without error. Here's my attempt:

```sh
# .env.local
HELLO=World
```

```js
// app.js
const http = require('http')
const PORT = 3000

const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' })
  res.end(`Hello ${process.env.HELLO}`)
})

server.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`)
})
```

```sh
$ dotenvx run --debug -f .env.local -- node app.js
Setting log level to debug
process command [node app.js]
options: {"env":[],"envFile":[".env.local"],"envVaultFile":[]}
loading env from .env.local (/Users/scottmotte/Code/dotenvx/playground/oct-09/.env.local)
{"HELLO":"World"}
HELLO set
HELLO set to World
[dotenvx@1.17.0] injecting env (1) from .env.local
executing process command [node app.js]
expanding process command to [/opt/homebrew/bin/node app.js]
Server is running on http://localhost:3000
^Creceived SIGINT
checking command process
{"_events":{},"_eventsCount":2,"_closesNeeded":1,"_closesGot":0,"connected":false,"signalCode":null,"exitCode":null,"killed":false,"spawnfile":"/opt/homebrew/bin/node","_handle":{"pid":24176},"spawnargs":["/opt/homebrew/bin/node","app.js"],"pid":24176,"stdin":null,"stdout":null,"stderr":null,"stdio":[null,null,null]}
sending SIGINT to command process
```

As you can see it doesn't raise any errors or warnings. It gracefully kills the process here: https://github.com/dotenvx/dotenvx/blob/v1.17.0/src/lib/helpers/executeCommand.js#L23

Can you please run yours in `--debug` mode. My guess is your kill process is not actually sending `SIGINT` though it might be claiming to. `--debug` will help reveal what might be going wrong. This part:

```
^C[12:59:11.602] WARN (my.service): SIGINT received: shutting down
```

That will help me see if code needs to be adjusted, but for now it looks correct.

**Comment by motdotla** [comment]
going to close right now as I don't think this is a bug, but if you can send me debug info and more info about the server and process manager you are using it will help us find the root cause.

**Comment by nfantone** [comment]
@motdotla Hi, thanks for taking a look.

I'm not sure what you're trying to reproduce, frankly. I showed you the exact line where the  log line is being printed. And, in my case, I get it every time. That logging shouldn't be there, regardless of whether you are able to reproduce it or not.

In general, I wouldn't expect any tool printing to stdout on my behalf, with a custom logger and format, unless explicitly enabled or requested to do so.

> My guess is your kill process is not actually sending SIGINT though it might be claiming to

My application receives a `SIGINT`, handles it and shuts down the process with a `process.exit(139)`. The log message you quoted comes from my own application. That's on purpose.

**Comment by motdotla** [comment]
> The https://github.com/dotenvx/dotenvx/issues/394#issuecomment-2407875971 is not handling event signals.

`SIGINT` is handled here: https://github.com/dotenvx/dotenvx/blob/v1.17.0/src/lib/helpers/executeCommand.js#L16

> I would still not expect dotenvx to print messages on exit, no matter how it may choose to handle downstream errors internally

if it didn't do this then it would swallow errors - are you suggesting to modify the code to swallow downstream process errors?

i need to better understand why it's not handling it for your scenario - as I can't duplicate. can you please share your scenario but with `--debug`.

**Comment by nfantone** [comment]
@motdotla Thank you for your answers.

> `SIGINT` is handled here:  https://github.com/dotenvx/dotenvx/blob/v1.17.0/src/lib/helpers/executeCommand.js#L16

Yes, I'm aware of that. My point still is that the difference between your snippet and my scenario is that *my process handles signals on its own, while yours doesn't* and simply delegates that signal to `dotenvx`.

> if it didn't do this then it would swallow errors - are you suggesting to modify the code to swallow downstream process errors?

Three comments here:

1. That's the thing, *this is not an error*. My service is exiting gracefully and `dotenvx` treats it differently.
2. I don't think the concept of "swallowing" applies here. Ideally, this should be completely transparent. If the underlying process dies, you may trap the error, run any cleanup tasks (if any) and simply *let the error bubble up to the OS runtime*. My process should behave the exact same way whether I'm bootstrapping it with `dotevnx run` or not.
4.`dotenvx` *should not print stuff*. What you decide on doing upon _actual_ errors, it's frankly up to you. But whatever you decide, my suggestion is that you don't log out stuff without users _explicitly allowing for it_.

> i need to better understand why it's not handling it for your scenario - as I can't duplicate. 

Apologies for repeating myself, but as mentioned, to reproduce the problem you'd need to handle signals on your own and exit the process with a non-zero exit code.


```js
// test.js

import process from 'node:process'

process.stdin.resume()

process.on('SIGINT', () => {
  console.log('Received SIGINT. Exiting with code 130...')
  process.exit(130)
})
```


And run it with and without `dotenvx` to see what I mean.

```sh
node test.js
^CReceived SIGINT. Exiting with code 130...

echo $?
130

yarn dotenvx run -- node test.js
[dotenvx@1.19.0] missing .env file (/Users/nicolas.fantone/dev/klarna/it/backend-interview-nodejs/.env)
? add one with [echo "HELLO=World" > .env] and re-run [dotenvx run -- node test.js]
[dotenvx@1.19.0] injecting env (0)
^CReceived SIGINT. Exiting with code 130...
Command exited with exit code 1: /private/var/folders/lh/jz6l0mjd2z10k001hrmnlnr40000gp/T/xfs-c41840da/node test.js
```

However, that's not the main point I'm trying to convey. IMHO, *none of the log lines you see above (except the one by `test`.js`) should be printed at all*. They should be _opt-in_ by default, not _opt-out_. At least, all the ones from the initialisation can be muted with `--silent`. The error at the end, however, can't be removed at all.

**Comment by motdotla** [comment]
thank you for the example. it allowed me to duplicate and create a solution for the core issue:

https://github.com/dotenvx/dotenvx/pull/402

it will go out as `1.19.1`

> dotenvx should not print stuff.

disagree.

thank you for using dotenvx. all the best.

**Comment by nfantone** [comment]
> disagree.

Feels like this needs a bit of elaboration on your part?

A process that's bootstrapping a child process should not hi-jack its standard out stream, unless required. Logs are used to convey information for users and are typically process by upstream logging systems that expects messages to conform to a certain format. `dotenvx` breaks all of that.

**Comment by motdotla** [comment]
give it a rest man. you are ignoring all the other use cases - particularly development which is and always will be dotenv(x)'s number 1 priority.

use --quiet for your use case.

errors go to stderr now.

**Comment by nfantone** [comment]
> particularly development which is and always will be dotenv(x)'s number 1 priority

I'm not sure I get what you're trying say and don't see how making logs being opt-in for the `run` command would hugely impact core use cases — but sure thing. It's your project, appreciate your work.

I also would like to make you aware that some other alternative tooling from the community, like `dotenv-cli`, handles this correctly.

**Comment by motdotla** [comment]
i'll mull on it. thank you.
