### ISSUE TITLE
Backslash not decrypted correctly

### ISSUE THREAD

**Issue by ntorrey** [dotenvx/dotenvx#406]
Using version 1.19.2
If I have a value like this:
`TEST='test\test'`
And I run `encrypt` and then `decrypt`, I get the following value:
`TEST='test\\test'`

**Comment by motdotla** [comment]
yes that was a purposeful change. you should still get the correct value back in usage though right? when you pass it to your script or app it displays only one backslash correct?

**Comment by motdotla** [comment]
dang it. it is. working on a patch. sorry about this! bad bug to sneak in.

**Comment by motdotla** [comment]
until then fall back to `1.17.0` or older. 

for binary installs their are instructions at https://dotenvx.sh

for npm just pin to 1.17.0

**Comment by motdotla** [comment]
effort happening here: https://github.com/dotenvx/dotenvx/pulls

**Comment by motdotla** [comment]
going out now as `v1.19.3`. once release finishes let me know if you run into any issues. thank you for reporting!

**Comment by ntorrey** [comment]
Awesome! Thanks for the quick turnaround!!

**Comment by motdotla** [comment]
i did a quick test myself with the binary installed to mac os. seems good now.

**Comment by ntorrey** [comment]
Yep, seems to work for me too! 👍
