### ISSUE TITLE
eciesjs ERR_PACKAGE_PATH_NOT_EXPORTED error

### ISSUE THREAD

**Issue by deisner** [dotenvx/dotenvx#418]
I'm running the Hello World example from the dotenvx README and I'm getting an ERR_PACKAGE_PATH_NOT_EXPORTED error:

```
 ~/dev/eciesjs-bug/hw$ ls                                                                                                                                              ✔  13:42:01
index.js
 ~/dev/eciesjs-bug/hw$ cat index.js                                                                                                                                    ✔  13:42:02
console.log('Hello ' + process.env.HELLO)
 ~/dev/eciesjs-bug/hw$ cat .env                                                                                                                                        ✔  13:42:03
HELLO=world
 ~/dev/eciesjs-bug/hw$ npx @dotenvx/dotenvx run -- node index.js                                                                                                       ✔  13:42:07
node:internal/modules/cjs/loader:598
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/deisner/.npm/_npx/fdacfd67f4da830d/node_modules/eciesjs/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:593:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/deisner/.npm/_npx/fdacfd67f4da830d/node_modules/@dotenvx/dotenvx/src/lib/helpers/decryptValue.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.11.1
```

The dotenvx dependency on eciesjs is resolving to the latest version (at the moment), v0.4.9, which was released a few hours ago:

```
~/dev/eciesjs-bug/hw$ (cd /Users/deisner/.npm/_npx/fdacfd67f4da830d && npm ls -a eciesjs)                                                                            
fdacfd67f4da830d@ /Users/deisner/.npm/_npx/fdacfd67f4da830d
└─┬ @dotenvx/dotenvx@1.20.0
  └── eciesjs@0.4.9
  ``` 
  
  I think this is triggering the error:
```
 ~/dev/eciesjs-bug/hw$ cat /Users/deisner/.npm/_npx/fdacfd67f4da830d/node_modules/@dotenvx/dotenvx/src/lib/helpers/decryptValue.js
const { decrypt } = require('eciesjs')
```

 I'm not sure if this is an eciesjs bug, or an issue with the way dotenvx is importing it. Please let me know, thanks!

**Comment by deisner** [comment]
OK, probably eciesjs: https://github.com/ecies/js/issues/802

**Comment by deisner** [comment]
Perhaps you can pin the version to eciesjs@0.4.8 in package.json -- the only dev on eciesjs lives in Japan, where it's 3AM right now.

**Comment by bryceg** [comment]
This broke our package also.  We pinned it through overrides in package.json for now, but ideally this package would pin its dependencies to avoid this in the future.

**Comment by mirasayon** [comment]
Same issue :(

**Comment by finack** [comment]
For our package.json and npm we added
```json
  "overrides": {
    "@dotenvx/dotenvx": {
      "eciesjs": "0.4.8"
    }
  }
```
and are running `npx @dotenvx/dotenvx run` instead of globally installing dotenvx and running it directly. Just make sure your do `npm install` or equivalent before running npx :)

**Comment by LinFeng1997** [comment]
@finack 

It looks great when I install dotenvx globally, how can I solve this problem if I install dotenvx via `curl -sfS https://dotenvx.sh | sh`?

**Comment by nalikhanoff** [comment]
problem is fixed with new update on [eciesjs](https://github.com/ecies/js/releases/tag/v0.4.10)

**Comment by kigawas** [comment]
Hi Community,

This has been fixed in v0.4.10, sorry for the inconvenience.

**Comment by mirasayon** [comment]
I sent PR that fixes this: #421

**Comment by motdotla** [comment]
thank you @kigawas for the amazing library. dotenvx would not be as great without it. 🙏

1.20.1 released everyone - https://github.com/dotenvx/dotenvx/actions/runs/11483050191

**Comment by motdotla** [comment]
also big thanks to everyone here helping to unblock each other - while you waited on us maintainers.

**Comment by motdotla** [comment]
> It looks great when I install dotenvx globally, how can I solve this problem if I install dotenvx via curl -sfS https://dotenvx.sh | sh?

to clarify, it did not affect anyone using dotenvx as a binary, because those were already built and released with a working eciejs version. only affected those installing with npm/pnpm/etc
