### ISSUE TITLE
Suppress all output

### ISSUE THREAD

**Issue by madtrick** [dotenvx/dotenvx#42]
Hi,

Thanks for making this. It's quite helpful :) 

I have a request. Could it be possible to add an option to supress all output from the tool? I would like to get read of this "info" messages

![image](https://github.com/dotenvx/dotenvx/assets/48772/6d83f85d-e9c0-4c18-96e2-26e04b94260c)

**Comment by motdotla** [comment]
you can do that now with `--quiet` 

```
dotenvx run --quiet -- node index.js
```

under the hood it says your log-level to error rather than info.

does that work for your needs?

(i realize haven't documented that anywhere outside of the `help` command. will add shortly)

**Comment by motdotla** [comment]
also, can i ask, how did you come across `dotenvx` ?
