### ISSUE TITLE
error TS2371: parameter initialization is not accepted in abstract function

### ISSUE THREAD

**Issue by palecek** [dotenvx/dotenvx#420]
Since TS version 5.3 (https://github.com/microsoft/TypeScript/issues/56525) it is not allowed default values in interface definition. It causes error you can see on the fig. So I suggest this patch https://github.com/dotenvx/dotenvx/pull/419

![image](https://github.com/user-attachments/assets/7c14faec-fa0e-4e6c-b990-7886c926d4e6)

**Comment by motdotla** [comment]
will go out as 1.20.1 or greater. thank you for the patch.
