### ISSUE TITLE
$'s are not properly handled when run via envx 

### ISSUE THREAD

**Issue by guycnicholas** [dotenvx/dotenvx#422]
Per the docs here: https://dotenvx.com/docs/env-file#syntax
My start command: "start": "dotenvx --debug run -- node src/app.js",
My .env file: START_STOP='$art$top'
The output
{"START_STOP":""}
START_STOP set
START_STOP set to 

I have found that I have to esc the `$` characters
START_STOP='\$art\$top'

**Comment by motdotla** [comment]
that's because it assuming interpolation: https://dotenvx.com/docs/env-file#interpolation

your solution is the correct one

i've added a detail to the docs to mention this:

<img width="633" alt="image" src="https://github.com/user-attachments/assets/0bbdbd28-5ae9-4453-9cc3-082a61539117">

**Comment by guycnicholas** [comment]
Thanks, but isn't that counter to the docs above? 
![image](https://github.com/user-attachments/assets/158baf7d-8c2c-4f99-88b3-40d06d70f614)

**Comment by guycnicholas** [comment]
The other odd part is that when running my server directly from VSCode using it works as I would expect.
`"configurations": [
		{
			"name": "Run Test-Server",
			"protocol":"inspector",
			"type": "node",
			"request": "launch",
			"console": "integratedTerminal",
			"skipFiles": [
				"<node_internals>/**/*.js"
			],
			"env": { "ENVIRONMENT_NAME": "local"},

			// Works if you open in VS Code the folder that contains all cchome repos
			"program": "${workspaceRoot}/src/app.js"
		},`

**Comment by motdotla** [comment]
you're right.

this is a historical artifact. dotenv for nodejs (using dotenv-expand) never differentiated between single, no quote, or double quote. it just expanded all.

but other libs like the ruby dotenv treat it as:

* no quotes - don't expand
* single quotes - don't expand
* double quotes - don't expand

i'm going to look into this and try to solve. also we have to solve for if the content is encrypted, and that also respecting quotes. bit tricky. 

until then anyone coming across this you will have to escape dollar signs if you don't want expansion.

**Comment by motdotla** [comment]
effort started here: https://github.com/dotenvx/dotenvx/pull/423

**Comment by motdotla** [comment]
releasing now as `1.21.0`. thank you for raising this.

**Comment by guycnicholas** [comment]
Thanks for fixing it.
