### ISSUE TITLE
Proposal: make `get` return non-zero if values were could not be decrypted

### ISSUE THREAD

**Issue by benjaminbauer** [dotenvx/dotenvx#427]
### Motivation
When using `dotenvx get` in a script to access single values, I had a quiet failure, because I did not set up the decryption correctly.

### Desired Behaviour
Make `dotenvx get` exit with a non-zero return code, when values are present, that could not be decrypted

Alternative w/o breaking current usage: add a `--strict` flag that switches to the described behaviour and keep the regular usage as is.

**Comment by motdotla** [comment]
have been considering this myself as well, but i want symmetry between `run` and `get` and so have some misgivings. it doesn't seem like `run` should exit/fail. dotenv as never done that if you missed an env.

maybe a `--strict` flag is the way to go.

i will mull on this one more.

can you give more detailed context of your scenario. how did you recognize the issue and then what did you do to patch it up? basically color in the story a bit more of the experience.

**Comment by benjaminbauer** [comment]
I am setting up a docker container for postgres. The image supports an env var, that [points to a file, that contains the admin password](https://github.com/docker-library/docs/blob/master/postgres/README.md#docker-secrets). In the Dockerfile, I mount my `.env` and the private key as a secret to then `dotenvx get KEY > /the-file-where-postgres-expects-the-password`. If I wired something wrong here and the decrytion fails, this quickly becomes a footgun. For now I use `dotenvx decrypt --stdout` which fails if the decryption fails. Drawback: I have to grep/sed out the value I want.

**Comment by benjaminbauer** [comment]
`run` could imo also benefit from a `strict` flag. But then again, I tend to be more on the static end of the typing preferences spectrum 😅

**Comment by motdotla** [comment]
ok this is really helpful.

likely going to be something like a `--strict` flag but this is also an opportunity to do some thinking and planning around 'validating' .env values. i do want dotenvx to support opt-in to that some day too. something along these lines: https://dev.to/schead/ensuring-environment-variable-integrity-with-zod-in-typescript-3di5

the decryption failing scenario and validating env values are somewhat related.

**Comment by motdotla** [comment]
effort started here https://github.com/dotenvx/dotenvx/pull/459

i think implementation will end up as:

* by default does NOT `process.exit(1)` on errors
* errors log to stderr
* add `--strict` flag and errors will log to stderr AND `process.exit(1)` will happen if one or more errors
