### ISSUE TITLE
adjust dotenvx help to display [options] following positional [command(s)]

### ISSUE THREAD

**Issue by benjaminbauer** [dotenvx/dotenvx#428]
```sh
touch .env.a
dotenvx set -f .env.a key value
```

### Observed
`error: missing required argument 'KEY'`

### Expected
`.env.a` shall contain an entry `key=value`

### Additional
oddly enough this works (no space between `-f` and `.env.a`)
```sh
dotenvx set -f.env.a key value
```

dotenvx version:`1.21.0`

**Comment by motdotla** [comment]
this is a parsing ambiguity when there are both positional arguments `KEY value` and flags `-f`. you have a few options but best practice is place flags at the end.

```sh
dotenvx set key value -f .env.a
```

option 2: `full flag name with =`

```sh
dotenvx set --env-file=.env key value
```

option 3: `instruct end of options with --`

```sh
dotenvx set -f .env -- key value
```

option 4: `no space (your example)`

```sh
dotenvx set -f.env key value
```

i considered having all instructions use `--` but I didn't like the verbosity just for this rare edge case. i think most users just place their flags at the end when they experience this.

thanks for bringing up but will leave as is. closing this.

**Comment by benjaminbauer** [comment]
Two thougts:

### Upate help
`dotenvx set -h` currently states:
```sh
Usage: dotenvx set [options] <KEY> <value>
```
Which does not hint to your mentioned solutions

### Promot the -f flag
Seems to me, that the -f flag could "global", i.e. `dotenvx -f <file(s)> set/get/decrypt/...` instead of being a flag to each command. Most, if not all dotenvx commands support this flag.

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/429

will go out as next release. great attention to detail. thank you!
