### ISSUE TITLE
Variable expansion/interpolation bugs (depth and self-reference)

### ISSUE THREAD

**Issue by kanaka** [dotenvx/dotenvx#433]
The parsing/handling of variable expansion doesn't handle some useful/interesting cases. This is with version 1.22 npm module installed.

There are both self-reference issues, default prefix issues, and depth issues.

For self-reference, I have an very common case in my .env files where I want to set a variable if it's not already set but this doesn't work with dotenvx:
```
TEST_USER=${TEST_USER:-tester} # result: "${TEST_USER:-tester}"
```

If you have a prefix in your default value, dotenv stops expanding:
```
TEST_TRIV=prefix-${BAR} # result: "prefix-${BAR}"
```

And if your expansion is too deep, extraneous stuff appears:
```
TEST_DEEP=${A:-${B:-${C:-${D:-${E:-}}}}} # result: ":-}}"
```

I believe at least the depth problems are somewhere in this vicinity: https://github.com/dotenvx/dotenvx/blob/main/src/lib/helpers/dotenvExpand.js#L11  Parameter/variable expansion is a recursive by nature and I don't think regexp alone has the power to parse a recursive grammars.

For the self-reference problem, my suspicion is that the contents of the env-file are loaded into a map all at once. And so self-reference gets the final version of the variable and loses earlier states that the variable was in when it occurred in order in the file.

My simple driver:
```
dotenvx = require('@dotenvx/dotenvx')
const res = dotenvx.config({path: ".env-test"})
Object.entries(res.parsed).sort().forEach(([k, v]) => console.log(`${k}=${v}`))
```

Here is my full `.env-test` file:
```
# Compare with correct behavior of shell command:
#     ( . .env-test; set | grep TEST_)

### These work

TEST_SIMPLE=${FOO:-bar}
TEST_DEEP1=${FOO:-${USER:-test}-suffix1}
TEST_DEEP2=${BAZ:-${BAR:-${FOO:-${USER:-test}-suffix1}-suffix2}-suffix3}


### The following are broken

# extraneous end curly braces:
TEST_DEEP3=${QUX:-${BAZ:-${BAR:-${FOO:-${USER:-test}-suffix1}-suffix2}-suffix3}-suffix4}
TEST_DEEP4=${QUXX:-${QUX:-${BAZ:-${BAR:-${FOO:-${USER:-test}-suffix1}-suffix2}-suffix3}-suffix4}-suffix5}

# prefix prevents continuing expansion:
TEST_DEEP5=${FOO:-prefix1-${USER:-test}}
TEST_DEEP6=${FOO:-prefix1-${USER:-test}-suffix1}
TEST_DEEP7=${BAR:-prefix2-${FOO:-prefix1-${USER:-test}-suffix1}-suffix2}

# both extraneous end curl and failure to expand
TEST_DEEP8=${QUXX:-prefix5-${QUX:-prefix4-${BAZ:-prefix3-${BAR:-prefix2-${FOO:-prefix1-${USER:-test}-suffix1}-suffix2}-suffix3}-suffix4}-suffix5}

# expansion is incomplete and incorrect:
TEST_RECUR1="${TEST_RECUR1:-} 234"
TEST_RECUR2=${TEST_RECUR2:-${USER:-test}-bar}
TEST_RECUR3=foo
TEST_RECUR3=prefix2-${TEST_RECUR3:-prefix1-${USER:-test}-suffix2}-suffix2
```

The correct behavior is this:
```
$ ( . .env-test; set | grep TEST_)
TEST_DEEP1=joelmartin-suffix1
TEST_DEEP2=joelmartin-suffix1-suffix2-suffix3
TEST_DEEP3=joelmartin-suffix1-suffix2-suffix3-suffix4
TEST_DEEP4=joelmartin-suffix1-suffix2-suffix3-suffix4-suffix5
TEST_DEEP5=prefix1-joelmartin
TEST_DEEP6=prefix1-joelmartin-suffix1
TEST_DEEP7=prefix2-prefix1-joelmartin-suffix1-suffix2
TEST_DEEP8=prefix5-prefix4-prefix3-prefix2-prefix1-joelmartin-suffix1-suffix2-suffix3-suffix4-suffix5
TEST_RECUR1=' 234'
TEST_RECUR2=joelmartin-bar
TEST_RECUR3=prefix2-foo-suffix2
TEST_SIMPLE=bar
```

Here is the dotenvx behavior:
```
$ node test.js
[dotenvx@1.22.0] injecting env (1) from .env-test
TEST_DEEP1=joelmartin-suffix1
TEST_DEEP2=joelmartin-suffix1-suffix2-suffix3
TEST_DEEP3=joelmartin-suffix1-suffix2-suffix3-suffix4}
TEST_DEEP4=joelmartin-suffix1-suffix2-suffix3-suffix4}-suffix5}
TEST_DEEP5=prefix1-${USER:-test}
TEST_DEEP6=prefix1-${USER:-test}-suffix1
TEST_DEEP7=prefix2-${FOO:-prefix1-${USER:-test}-suffix1}-suffix2
TEST_DEEP8=prefix5-${QUX:-prefix4-${BAZ:-prefix3-${BAR:-prefix2-${FOO:-prefix1-${USER:-test}-suffix1}-suffix2}-suffix3-suffix4}-suffix5}
TEST_RECUR1=${TEST_RECUR1:-} 234:-} 234
TEST_RECUR2=${TEST_RECUR2:-${USER:-test}-bar}
TEST_RECUR3=prefix2-prefix2-${TEST_RECUR3:-prefix1-${USER:-test}-suffix2}-suffix2-suffix2
TEST_SIMPLE=bar
```

**Comment by motdotla** [comment]
darn, i'll take a look at these. i actually thought we had these covered and had test coverages for them as well.

**Comment by motdotla** [comment]
all this said, it might be time dotenvx built its own expansion engine that properly subscribes to bash's.

**Comment by kanaka** [comment]
From my experience self-referencing is a pretty common way to set a default value without having to impose extra constraints on the source or consumer by having two different names on each side. It's also the typical way to do appending/accumulating when you don't know ahead of time how many times you will do an append. For example, I often want to load several environment files iteratively with earlier ones able to affect later ones (and each env file adds to end of a single variable).

I still get the same behavior with 1.22.1:
```
TEST_PREFIX=prefix1-${BAR:-test}
```
Results in `prefix1-${BAR:-test}` and it should be `prefix1-test`. I.e. it doesn't continue resolving internal expansions if there is a prefix before the expansion.

I personally would like to see dotenv/dotenvx support functionality equivalent or greater than docker-compose env-file expansion. I use depth, self-reference, prefix, etc all the time in that context and would like to be able to load env-files in JS or ClojureScript with the same expansion/resolution functionality.

**Comment by motdotla** [comment]
> From my experience self-referencing is a pretty common way to set a default value without having to impose extra constraints on the source or consumer by having two different names on each side

strong point

---

> I still get the same behavior with 1.22.1:

hmm. what machine are you on? I can't reproduce. here's my attempt:

```
# .env
TEST_PREFIX=prefix1-${BAR:-test}
```

```
$ dotenvx get
{"TEST_PREFIX":"prefix1-test"}
```

---

> I personally would like to see dotenv/dotenvx support functionality equivalent or greater than docker-compose env-file expansion

I like this thinking. I'll work towards it. I've been wanting to internalize dotenvx-expand to its own engine anyways.

**Comment by kanaka** [comment]
Ubuntu 22.04 with node 22.

Tested in on my macOS too and got the same result:
```
 ~/tmp $ sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60

 ~/tmp $ node --version
v21.7.2

 ~/tmp $ cat .env-test1
TEST_PREFIX=${FOO:-prefix1-${BAR:-test}}

 ~/tmp $ cat test-dotenvx.js
#!/usr/bin/env bash
dotenvx = require('@dotenvx/dotenvx')
const res = dotenvx.config({path: ".env-test1"})
Object.entries(res.parsed).sort().forEach(([k, v]) => console.log(`${k}=${v}`))

 ~/tmp $ node test-dotenvx.js
[dotenvx@1.22.1] injecting env (0) from .env-test1
TEST_PREFIX=prefix1-${BAR:-test}
```

**Comment by kanaka** [comment]
For completeness:

Here is using the command line directly on macOS/node-21 (with `.env-test1` renamed to `.env`):
```
$ node_modules/.bin/dotenvx get
{"TEST_PREFIX":"prefix1-${BAR:-test}"}
```

Here is using the standard node docker image (which should isolate from most environmental weirdness):
```
$ docker run -it --rm -w /tmp node bash
root@419ac66c92c9:/tmp# node --version
v23.1.0
root@419ac66c92c9:/tmp# npm i @dotenvx/dotenvx
...
added 30 packages in 1s
...
root@419ac66c92c9:/tmp# echo 'TEST_PREFIX=${FOO:-prefix1-${BAR:-test}}' > .env
root@419ac66c92c9:/tmp# cat .env
TEST_PREFIX=${FOO:-prefix1-${BAR:-test}}
root@419ac66c92c9:/tmp# node_modules/.bin/dotenvx get
{"TEST_PREFIX":"prefix1-${BAR:-test}"}
```

**Comment by motdotla** [comment]
that's a slightly different example. and I can reproduce that:

```
# .env
TEST_PREFIX=${FOO:-prefix1-${BAR:-test}}
```

```
{"TEST_PREFIX":"prefix1-${BAR:-test}"}
```

**Comment by motdotla** [comment]
ok, `1.23.0` updates the logic to support all of this.

it also includes one improvement over docker-compose's parser:

`ESCAPE_EXPAND=\$EXPAND` becomes `$EXPAND` rather than `\\`

There is one exception:

```
TEST_RECUR3=foo
TEST_RECUR3=prefix2-${TEST_RECUR3:-prefix1-${USER:-test}-suffix2}-suffix2
```

that one is a major change and part of me wants to discourage users from being permitted that ability. i'll think on it more and i welcome anyone else (yourself included) to add additional thoughts here.

**Comment by kanaka** [comment]
@motdotla Thanks for the quick turnaround! I'd still love to see linear processing of variables from the env file so that bash/compose style append functionality can be used. Getting append support in env files was actually why I came looking for dotenv/dotenv-expand/dotenvx. We have a project that relies on that behavior of docker-compose and we were hoping to be able to use the same env files in other ClojureScript/JS applications. I'll file a separate ticket, so that it can be considered separately. I think it would imply that expansion would need to be done during initial parsing so that certainly would be a bigger change that what you just did (I was surprised by how small your change was TBH).

**Comment by kanaka** [comment]
@motdotla I filed a ticket on the append/update capability: https://github.com/dotenvx/dotenvx/issues/441

**Comment by AdiMarianMutu** [comment]
@motdotla We are still having this issue (`v1.26.0`).

Example of the `.env` file content:

```
DB_MAIN="${ENV_DB_MAIN:-mysql://root:root@localhost:3306/local-nora}"
```

Produces `${ENV_DB_MAIN:-mysql://root:root@localhost:3306/local-nora}` instead of `mysql://root:root@localhost:3306/local-nora` when the `ENV_DB_MAIN` var is **not** set.

**Comment by Mihai-Razvan** [comment]
> @AdiMarianMutu hmm. i can only reproduce this if ENV_DB_MAIN is set inside the `.env` file further up. Is that the case? you have inside that same .env file `ENV_DB_MAIN=''` ?
> 
> edit: actually, I cannot reproduce this at all. I was misreading my test. All seems in order.
> 
> @AdiMarianMutu can you double check you aren't accidentally using single quotes? (though the example you shared is definitely double quotes)
> 
> #476

Hi @motdotla, I'll take over from Adi here. The answer is no, we aren't using single quotes

**Comment by motdotla** [comment]
ok i cant reproduce then. are you certain you are on the latest version of dotenvx. 

are you using multiple .env files? and is it possible you are using the old dotenv somewhere and that is presetting it?

you'll have to give me more info since this is unable to be reproduced.

**Comment by Mihai-Razvan** [comment]
@motdotla For the first 2 questions (are you using multiple .env files? and is it possible you are using the old dotenv somewhere and that is presetting it?) the answer is NO.
This is the way we import the envs:
`
import dotenvx from '@dotenvx/dotenvx;
dotenvx.config({ override: true });`
`

We are using a monorepo with Nx and NextJS

**Comment by motdotla** [comment]
i can't reproduce

```
DB_MAIN="${ENV_DB_MAIN:-mysql://root:root@localhost:3306/local-nora}"
```

```
// index.mjs
import dotenvx from '@dotenvx/dotenvx'
dotenvx.config({ override: true, debug: true })

console.log(process.env.DB_MAIN)
```

NextJS uses its own dotenv that I believe does not support expansion so your problem is likely there.

Please submit your issue to them or instead of using dotenvx as an import, use `dotenvx run -- npm dev`.


(P.S. you can use the `debug` option to debug your problems like these. `dotenvx.config({ override: true, debug: true })`)

**Comment by motdotla** [comment]
@Mihai-Razvan you can follow the next.js guide here: https://dotenvx.com/docs/package-managers/npm#next

**Comment by AdiMarianMutu** [comment]
> @Mihai-Razvan you can follow the next.js guide here: https://dotenvx.com/docs/package-managers/npm#next

This is irrelevant.

We are using the JS API to inject the entire `.env` var file during run-time rather than BEFORE running the build/serve process. We have our reasons to do this which right now I'm not going to explain.

I've also tried to add the `convention: 'nextjs'` property to the `config` method but it still does not expand the variables.

The expansions fails even with simple variables like: `NEXT_PUBLIC_IS_LOCAL_DEV_ENV="${ENV_IS_LOCAL_DEV_ENV:-true}"`

This is the result from the `debug` logs (enabled by setting the `debug` property to `true`)

```
NEXT_PUBLIC_IS_LOCAL_DEV_ENV set
NEXT_PUBLIC_IS_LOCAL_DEV_ENV set to ${ENV_IS_LOCAL_DEV_ENV:-true}
```

I think it should be

```
NEXT_PUBLIC_IS_LOCAL_DEV_ENV set
NEXT_PUBLIC_IS_LOCAL_DEV_ENV set to true
```

**Comment by motdotla** [comment]
@AdiMarianMutu possibly related: https://github.com/nrwl/nx/discussions/27435

**Comment by AdiMarianMutu** [comment]
> @AdiMarianMutu possibly related: [nrwl/nx#27435](https://github.com/nrwl/nx/discussions/27435)

I confirm that using the CLI fixes the issue as long as the `--overload` param is provided, which is something we want to avoid too.

However, I think that you could do some slight changes to `dotenvx` to fix this behavior (as most probably the maintainers from `NX` will not agree to add what requested in the https://github.com/nrwl/nx/discussions/27435 discussion):

Yesterday during my tests I saw this in [lib/helpers/parse.js#38](https://github.com/dotenvx/dotenvx/blob/main/src/lib/helpers/parse.js#L38), that line should basically fix the issue as if the variable does already exist it should just copy it over (and I confirm that `NX` does the interpolation by using the `shell` syntax, so at that point the variable is already expanded), but somewhere down the line, the `this.parsed[key]` var is assigned once again to the original (unexpanded) value from the `.env` file.

I'll try to take a deeper look into this myself later, maybe I can come up with a solution and I'll open a PR.

**Comment by motdotla** [comment]
can you please set up an example repo for me and I will help debug. 

But your ideas here are breaking (try making the change yourself on dotenvx and running the tests), and I dont plan to make them. dotenv and dotenvx have always respected what is set first in process.env and will never change that behavior. 

The issue here is that nx is somehow STILL setting your value to process.env before dotenvx has a chance to read it and set it. 

This is typically a config issue. So if you can set up an example repo for me, I can clone it, and solve for you guys and you can get this headache behind you.

**Comment by AdiMarianMutu** [comment]
> However I don't know what side-effects may this have, can you take a look?

I don't have much free time on my hands so I'll try to set-up that repo for you when possible (for the moment the solution is to avoid using `override: true` in `dotenvx.config` which luckily does not break anything on our side as we just have recently made some major changes to how we manage the env vars)

Regarding the last part, this is just a discussion, that's why I didn't open a new issue, also, I'm aware that what I've proposed may/will break some things, that's why I've specified `However I don't know what side-effects may this have, can you take a look?`.

So it wasn't my/our intent to upset you :)

**Comment by rhyek** [comment]
Is self-referencing variable expansion meant to be supported with the latest version?

```ts
import { parse } from '@dotenvx/dotenvx';

process.env.MSG = 'world';
process.env.NODE_OPTIONS = '--max-old-space-size=1024';

const env = parse(
  `
  HELLO=$MSG
  NODE_OPTIONS="$NODE_OPTIONS --inspect"
  `,
  {
    override: true,
  }
);

console.log(env.HELLO);
console.log(env.NODE_OPTIONS);
```
The above outputs:
```bash
world
$NODE_OPTIONS --inspect
```

**Comment by motdotla** [comment]
@rhyek thank you for catching and for the easily reproducible example. Fix is being worked here: https://github.com/dotenvx/dotenvx/pull/536

(this might fix things for others above as well. core issue was that prior-set process.env variables were not being respected for self-referencing variable expansion)

**Comment by motdotla** [comment]
release going out now as [`v1.38.3`](https://github.com/dotenvx/dotenvx/actions/runs/13533059356). thank you for using dotenvx 🙏

**Comment by rhyek** [comment]
@motdotla that solved it. Thanks!
