### ISSUE TITLE
Environment Variable Loading Order Issue with Single Quotes

### ISSUE THREAD

**Issue by asfktz** [dotenvx/dotenvx#435]
It seems that single quotes affect the loading order. For example, consider the following environment files:

### ⚠️ Single Quotes

**.env**
```bash
HELLO='env'
```

**.env.development**
```bash
HELLO='env development'
```

**Returns:**
```
Hello: env
```

### ✅ Double Quotes

**.env**
```bash
HELLO="env"
```

**.env.development**
```bash
HELLO="env development"
```

**Returns:**
```
Hello: env development
```

### ✅ Without Quotes

**.env**
```bash
HELLO=env
```

**.env.development**
```bash
HELLO=env development
```

**Returns:**
```
Hello: env development
```

---

The command I used to test it:

**index.js**
```js
console.log("HELLO:", process.env.HELLO);
```

**Command:**
```bash
npx dotenvx run --convention=nextjs -- node ./index.js
```

**Version:**
@dotenvx/dotenv@^1.22.0

**Comment by motdotla** [comment]
oh wow. good catch and a bad bug. i see the core of the problem. working on a fix.

**Comment by asfktz** [comment]
Thanks @motdotla!
