### ISSUE TITLE
.gitignore modification

### ISSUE THREAD

**Issue by radoslavkarlik** [dotenvx/dotenvx#44]
Works good but why is it updating the `.gitignore` file? I just need it to read the config. If I wanted to ignore my env files, I would do it myself. How can I turn it off?

**Comment by bbeesley** [comment]
This. It's particularly annoying since our env config isn't even in a path that starts with `.env`.

Reading environment variables from a file shouldn't be an operation that writes to my files.

**Comment by motdotla** [comment]
i personally liked the convenience but you both make good points. i think i will change this and instead make it a separate command you can run

**Comment by motdotla** [comment]
done. https://github.com/dotenvx/dotenvx/pull/45

upgrade to `0.11.0` or above (release running: https://github.com/dotenvx/dotenvx/actions/runs/7658262528)

also, can i ask, how did you each find dotenvx?

**Comment by motdotla** [comment]
cc @radoslavkarlik @bbeesley

**Comment by bbeesley** [comment]
> also, can i ask, how did you each find dotenvx?

By reading the docs for dotenv. Thanks a lot for the rapid turnaround on that, that's awesome.
