### ISSUE TITLE
[BUG] Interpolation been executed in literal value

### ISSUE THREAD

**Issue by jvitor83** [dotenvx/dotenvx#457]
When a variable with interpolation uses another variable who have literal value, but this literal has a "env var format", it try to interpolate eitherway.

Example:
```.env
# .env
VAR_WITH_LITERAL_VALUE='${THIS_IS_A_LITERAL_VALUE} empty'
SOME_VAR="Why"
ANOTHER_VAR="${SOME_VAR} is ${VAR_WITH_LITERAL_VALUE}"
```

```bash
# command
dotenvx run -f .env -- printenv
```

```bash
# output
[dotenvx@1.24.4] injecting env (3) from test.env
VAR_WITH_LITERAL_VALUE=${THIS_IS_A_LITERAL_VALUE} empty
SOME_VAR=Why
ANOTHER_VAR=Why is  empty
```

Expect:
`ANOTHER_VAR` to have the value `Why is ${THIS_IS_A_LITERAL_VALUE} empty`

**Comment by motdotla** [comment]
effort started here https://github.com/dotenvx/dotenvx/pull/458

**Comment by motdotla** [comment]
going out now as `1.24.5`. 

thanks for using dotenvx and if you really like dotenvx, keep an eye out for when we release `dotenvx pro`. thanks!
