### ISSUE TITLE
Not Loading .env

### ISSUE THREAD

**Issue by zach-pp** [dotenvx/dotenvx#46]
I'm not able to use the contents of .env, while .env.{ENVIRONMENT} works fine.

Contents of .env located @ C:\Users\{PATH}\apps\web\\.env
> HELLO="local"

Output of debug execution:
```
> dotenvx run --debug -- next dev

process command [next dev]
options: {"envFile":".env"}
loading env from C:\Users\{PATH}\apps\web\.env
{}
[dotenvx@0.11.0] injecting env (0) from .env

```

Thanks!

**Comment by motdotla** [comment]
i cannot reproduce this yet, but i also haven't tested dotenvx with pnpm yet. i'll check that.

another thought i have is maybe it is a permissions setup on your .env file?

```
ls -al .env
-rw-r--r-- .env
```

is it a readable file?

**Comment by motdotla** [comment]
if you pass `--env-file=.env` directly, does that work?

**Comment by motdotla** [comment]
bizarre. if you change the filename from `.env` to `.something` and then load that like

```
dotenvx "run" "--debug" "--env-file=.something" "--" "next" "dev"
```

does that work?

and then if you try creating a brand new `.env` file, does that work?

this will exhaust any other ideas i have and then i will starting trying out pnpm.
