### ISSUE TITLE
error code: `[INVALID_PRIVATE_KEY]`

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#465]
### Are you getting this error?

```sh
[INVALID_PRIVATE_KEY] could not decrypt KEY using private key 'DOTENV_PRIVATE_KEY=priv...'
```

### How to fix:

Check your `DOTENV_PRIVATE_KEY`. Likely you are using the incorrect one - maybe one for a different environment or for a different project.

### More

Still tripped up? Leave your comment below and I'll help debug for you. Suggestions also welcome!

**Comment by motdotla** [comment]
closing this but if you run into this error and need help just @ me @motdotla. I will re-open and help. This issue is for helping each other debug configuration errors around encryption/decryption.

**Comment by whargrove** [comment]
@motdotla I am seeing this issue when trying to use dotenvx from a docker container.

I am running the container with the `--env-file=.env.keys` flag to set the private keys from .env.keys into the container environment. (Not using `--env=...` as suggested by <https://dotenvx.com/docs/platforms/docker>.)

When I try to read the encrypted property from `sh` in the container I get this error:

```
dotenvx get GOOGLE_PRIVATE_KEY -f .env.development
[INVALID_PRIVATE_KEY] could not decrypt GOOGLE_PRIVATE_KEY using private key 'DOTENV_PRIVATE_KEY_DEVELOPMENT="SNIP'
```

(Note the leading `"` in the value.)

If I use the `docker run --env` flag and set the private key directly without a leading quote, it resolves the issue. e.g. `docker run --env="DOTENV_PRIVATE_KEY_DEVELOPMENT=notasecret" ...`

Likewise, if I remove the wrapping `"` in the .env.keys file that was generated by `dotenvx set` then importing .env.keys via `docker run --env-file=.env.keys ...` works as expected.

**Comment by motdotla** [comment]
this is a limitation of docker's --env-file. it doesn't support double quotes. can you believe that?!

that said, i'd like to make this less of a gotcha for developers. so maybe I'll default the `.env.keys` generation to NOT use double quotes. should be safe to do so.

**Comment by motdotla** [comment]
releasing as `1.28.0`: https://github.com/dotenvx/dotenvx/compare/v1.27.0...v1.28.0

thanks for sharing the context here so well.

**Comment by whargrove** [comment]
@motdotla You're welcome and thanks for the quick turn-around! 🎉
