### ISSUE TITLE
"dotenvx set key" without providing value should ask for input to avoid secret value being stored in shell history

### ISSUE THREAD

**Issue by prabirshrestha** [dotenvx/dotenvx#468]
**Problem:**

Currently `dotenvx set key` is not possible and will fail with `error: missing required argument 'value'`. I prefer to never type secrets in the command line prompt as it is easily visible in the shell history.

Here is an example of my fish shell history for `dotenvx set a b` and `dotenvx set c d` which can be found at `~/.local/share/fish/fish_history`. Notice how the secret b and d is in plain text.

```
- cmd: dotenvx set a b
  when: 1732605285
- cmd: dotenvx set c d
  when: 1732605287
```

If some malicious program uploads that file, they will have access to the secrets. Another example can be when I'm sharing screen with others and use Ctrl+R to scroll through previous history of the shell.

**Solution:**

When using `dotenvx set key`. Ask for input and let the user paste or type the value then can press a command such as ctrl+d to save it. Do note that enter key might not work as some may want to use new lines as a value.

Example from ansible. https://docs.ansible.com/ansible/latest/vault_guide/vault_encrypting_content.html

Ansible explicitly even provides information to the user so they know what to do.

```
Reading plaintext input from stdin. (ctrl-d to end input, twice if your content does not already have a new line)
```

Workaround:

For fish shell is to use `fish --private` which will print out `fish is running in private mode, history will not be persisted.` and not save it in history. Other shells has similar features.

**Comment by motdotla** [comment]
Thanks for bringing up the idea. 

I'll consider it for the future but right now I think it complicates the usage too much of set. 

Furthermore, the solution already exists using `encrypt`.

1. Use text editor to set plaintext value in `.env` file
2. Run `dotenvx encrypt`
