### ISSUE TITLE
Encrypt and decrypt functions are not exported even though they still exist in the type information

### ISSUE THREAD

**Issue by tjjalava** [dotenvx/dotenvx#469]
It seems that in #410 `encrypt`, `decrypt` and `set` functions were removed from `main.js`. They still exist in `main.d.ts` though, and that caused a runtime error in our code after upgrade from v1.14.2 to v1.22.0, since we were using `dotenvx` directly from typescript/node without using the cli.

I guess that our way of using the library is not supported? Or do you think it would be possible to bring those functions back, so the library could be used from node applications without the cli?

**Comment by motdotla** [comment]
oof, sorry about not removing from the types file!

can you tell me more about how/why you're using those from the node rather than the command line? wouldn't you just need `config` and/or `parse` from code? context here can give me better insight on whether to add them back in or not. i've personally never found i need them in runtime code. are you building tooling on top of dotenvx possibly that wants to make use of those?

**Comment by tjjalava** [comment]
Sure, we have this rather restricted environment where we need to run the app on a bastion host. There was a security concern about leaving an unencrypted env-file lying around on the host, so we added dotenvx to the mix. We also didn't want to copy the env.keys-file to the bastion, but pass the decryption key to the app as an environment value. And, in addition to all this, there's a couple of env-vars in .env that shouldn't be encrypted, because of "reasons" 😬 (yeah, I know, it's a mess).

So I made a script that encrypts the env-file on localhost using dotenvx exported functions, because I could get the encrypted content and the decryption key straight from the function's return value. Then I add the few required unencrypted values to the end of the encrypted env-file, sync it to the bastion host and pass the decryption key to the app by environment. 

I'm pretty sure that by rethinking the whole setup we wouldn't need to use the exported functions at all, so I guess it's fine if you want to drop them for good. 👍

**Comment by motdotla** [comment]
Smart setup.

Support was recently added for excluding keys:

<img width="1662" alt="image" src="https://github.com/user-attachments/assets/fadf2cbe-e3b3-4fa8-8334-21dd6afe146c">

So maybe you could modify your script to something like this?

```
#!/bin/bash
# encrypt.sh
dotenvx encrypt -ek KEY1 -ek KEY2
```

Then you can execute that simple as `./encrypt.sh` or if you prefer `DOTENV_PRIVATE_KEY=<yourprivatekey> ./encrypt.sh` (dotenvx will respect DOTENV_PRIVATE_KEY set if no .env.keys file is present)

And then on your bastion server leave as is which I'm guessing is something like this:

```
DOTENV_PRIVATE_KEY=<yourprivatekey> dotenvx run -- yourcommand
```

Would that work?

**Comment by tjjalava** [comment]
> Support was recently added for excluding keys:

That's nice!

> So maybe you could modify your script to something like this?
> 
> ```
> #!/bin/bash
> # encrypt.sh
> dotenvx encrypt -ek KEY1 -ek KEY2
> ```
> 
> Then you can execute that as `./encrypt.sh` or if you prefer `DOTENV_PRIVATE_KEY=<yourprivatekey> ./encrypt.sh` (dotenvx will respect DOTENV_PRIVATE_KEY set if no .env.keys file is present) to generate your partially encrypted .env file.
> 
> And then on your bastion server leave as is which I'm guessing is something like this:
> 
> ```
> DOTENV_PRIVATE_KEY=<yourprivatekey> dotenvx run -- yourcommand
> ```
> 
> Would that work?

Yes, I'll look into this once I have time. I'm sure that I can get it to work without using the exported functions. Thanks!
