### ISSUE TITLE
Support unaltered STDOUT from `dotenvx run`

### ISSUE THREAD

**Issue by benjaminbauer** [dotenvx/dotenvx#470]
### Use case
I want to use the result (STDOUT) of a command I run. E.g. `result=$(dotenvx run -- my_command)`

### Status quo
`result` contains
```
[dotenvx@1.25.1] injecting env (1) from .env

my output
```

#### Use STDERR for dotenx runs output
so one could `result=$(dotenvx run -- my_command 2>/dev/null)`
#### Add a `-q/--quiet` flag to `run`
When setting this flag `run` does not emit any output if it runs w/o errors

I would prefer the second solution. In the first solution (to my limited bash knowledge) I would in any case also hide the STDERR of `my_command`

**Comment by motdotla** [comment]
`--quiet` already exists for this. You can find it under the Advanced section.

Admittedly there is a long list of advanced features there. 

Thanks for using dotenvx!

**Comment by motdotla** [comment]
oh and hi again @benjaminbauer ! i just want to say again your idea here was great https://github.com/dotenvx/dotenvx/issues/427. i've been using `--strict` myself now and really enjoying it.

**Comment by verheyenkoen** [comment]
This should be in the [library docs](https://dotenvx.com/docs/advanced#library) as well. I had to come all the way here to find that this is in fact possible. There is no doc listing all the options for the `config()` method.

**Comment by verheyenkoen** [comment]
@motdotla I meant the `quiet` option in the `config()` method. Does not seem to be mentioned in the docs. It is in the CLI flags however.

**Comment by verheyenkoen** [comment]
@motdotla Great!

Maybe nitpicking here but I noticed the title of these docs sections are `dotenvx.config(quiet: true)` but this concerns an options object so it should actually be `dotenvx.config({ quiet: true })`. Could be misleading to new JS developers.
