### ISSUE TITLE
How to use `set` simply programmatically

### ISSUE THREAD

**Issue by Azuka** [dotenvx/dotenvx#481]
Hi,

I know this was undocumented, but it looks like `set` was removed in #410, although it was still present in the typescript declaration until commit https://github.com/dotenvx/dotenvx/commit/2aa6606. I have a use-case for updating an env file based on values from a Kubernetes configmap yaml for local development. 

```typescript
import { set } from '@dotenvx/dotenvx';
import { writeFileSync } from 'node:fs';
const envFile = `${process.cwd()}/.env.dev.${env}`;

//...

for (const k in configmap) {
  const output = set(k, configmap[k], envFile, false);
  output.changedFilepaths.forEach((_, i) => {
    const processedEnvFile = output.processedEnvFiles[i];
    writeFileSync(processedEnvFile.filepath, processedEnvFile.envSrc, {
      encoding: 'utf8',
    });
  });
}
```

**Comment by motdotla** [comment]
ah interesting. maybe I should add it back. 

can you give me a little more context? like tell a story here of why you do things this way, etc. it will help me determine. 

i'm trying to keep dotenvx simple (limited surface area) but also recognize there will be new use cases like this one that come along.

**Comment by motdotla** [comment]
@Azuka ^

**Comment by Azuka** [comment]
> ah interesting. maybe I should add it back.
> 
> can you give me a little more context? like tell a story here of why you do things this way, etc. it will help me determine.
> 
> i'm trying to keep dotenvx simple (limited surface area) but also recognize there will be new use cases like this one that come along.

Apologies. I was out on vacation. 

My use-case was just a generic programmatic way to update an env file with additional values. Several cases I've used:

- Reading a helm deployment values file to populate a local environment file for developers
- Bootstrapping an auth server running in Docker/podman and writing the generated certificates and credentials to a local env file.

It looks like `dotenvx`'s code is built to support cli usage, but it would benefit from exposing the underlying primitives for reading/writing. I haven't found anything else (perhaps I haven't searched well enough) in the js/ts space that does that.

**Comment by motdotla** [comment]
helpful, thanks Azuka. i will re-expose `set` again.

**Comment by motdotla** [comment]
available in `1.31.0` or greater

<img width="1834" alt="image" src="https://github.com/user-attachments/assets/bc42e4ee-05b8-431b-acf6-728d869be3b2" />

**Comment by motdotla** [comment]
@Azuka a heads up, the newest version `1.34.0` now writes to the file for you: https://github.com/dotenvx/dotenvx/pull/517

**Comment by Azuka** [comment]
> [@Azuka](https://github.com/Azuka) a heads up, the newest version `1.34.0` now writes to the file for you: [#517](https://github.com/dotenvx/dotenvx/pull/517)

Thank you so much, @motdotla. Much appreciated!
