### ISSUE TITLE
error code: `[MISSING_ENV_FILE]`

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#484]
### Are you getting this error?

```sh
[MISSING_ENV_FILE] missing .env file (/path/to/.env)'
```

It means a .env* file you are trying to access is missing. In some cases you can ignore this depending on your setup. For example, maybe your process looks for a `.env.local` file but you don't have or need one.

### How to fix:

Create the file. Something like this:

```
$ echo "HELLO=World" > .env
```

### More

Still tripped up? Leave your comment below and I'll help debug for you. Suggestions also welcome!

**Comment by motdotla** [comment]
closing this but if you run into this error and need help just @ me @motdotla. I will re-open and help. This issue is for helping each other debug errors around missing .env files.

**Comment by roderik** [comment]
@motdotla is there a way to pass the ignore when using it programmatically? I tried quiet but that does not work

```ts
      let { parsed: currentEnv } = config({
        path: envFile,
        logLevel: "error",
        quiet: true,
      });
```

**Comment by motdotla** [comment]
yes, you can pass `ignore: ['MISSING_ENV_FILE']`

<img width="1810" alt="image" src="https://github.com/user-attachments/assets/3e27b3e0-1138-4b0e-9c99-06f568039d3e" />

**Comment by mdesousa** [comment]
hi @motdotla , loving `dotenvx` 👍 on this issue: it's be nice if the `.local` files were considered optional and didn't generate an error. thanks!

**Comment by motdotla** [comment]
@mdesousa that's a fair point. are you using with next.js? you could use the convention (which won't error) https://dotenvx.com/docs/advanced/run-convention-nextjs

**Comment by mdesousa** [comment]
we are using convention with `flow`... thought the only difference was the priority given to `.local` files. are they also different in treating them as optional / required? (although [their docs](https://www.npmjs.com/package/dotenv-flow) make them sound like they should be optional)

**Comment by motdotla** [comment]
@b-bot what framework are you using? if that is happening then it is likely a framework loading .env. 

(keep in mind that the convention ALSO attempts to load .env in addition to .env.local)

https://dotenvx.com/docs/advanced/get-key-convention-nextjs

**Comment by motdotla** [comment]
@Mann9199 I've just now added a docker-compose guide for you https://dotenvx.com/docs/platforms/docker-compose

If your file is missing likely it is something in your Dockerfile - not `COPY`ing over the encrypted .env file likely.

**Comment by doughmination** [comment]
> hey [@motdotla](https://github.com/motdotla) I'm also using docker compose, like [@Mann9199](https://github.com/Mann9199) but I still get the error, but it's loading my .env file fine? I have it setup so the compose.yml uses:

Was able to figure it out after some tweaking, if anyone is here for docker issues: Make the `Dockerfile` uses the dotenvx command and mount the .env files as volumes (ie `- ./.env:/app/.env:ro`)

**Comment by motdotla** [comment]
@abbylyra tomorrow when I release `1.59.0` it will create it by default.

https://github.com/dotenvx/dotenvx/pull/771

Pass `--no-create` to prevent file creation.

**Comment by pejalo** [comment]
Hey there @motdotla pardon me if I'm missing something. I'm just trying to specify the name of one `.env*` file.

.env.test
```.env
TEST_KEY=value
```

script.js
```js
import '@dotenvx/dotenvx/config'
console.log(process.env.TEST_KEY)
```

package.json
```json
{
  "type": "module",
  "scripts": {
    "go": "dotenvx run -f .env.test --ignore=MISSING_ENV_FILE -- node script.js"
  },
  "dependencies": {
    "@dotenvx/dotenvx": "^1.75.1"
  }
}
```

```sh
test % node -v
v24.15.0
test % npm -v
11.12.1
test % npm run go

> go
> dotenvx run -f .env.test --ignore=MISSING_ENV_FILE -- node script.js

⟐ injected env (1) from .env.test
☠ [MISSING_ENV_FILE] missing file (.env). fix: [https://github.com/dotenvx/dotenvx/issues/484]
⟐ injected env (0) · dotenvx@1.75.1
value
test %
```
