### ISSUE TITLE
switch to undici's `request`

### ISSUE THREAD

**Issue by SuperchupuDev** [dotenvx/dotenvx#57]
it's more than 3x faster (benchmark from https://twitter.com/matteocollina/status/1752740881554100669)

![image](https://github.com/dotenvx/dotenvx/assets/53496941/62fb6f30-fc4d-4d5e-9470-e8111bdd8cc8)

**Comment by motdotla** [comment]
would welcome someone to take the PR for this one.

**Comment by motdotla** [comment]
speed is less important here though than reliability. but seems like undici has been around long enough though to be provably reliable.
