### ISSUE TITLE
support first-class built-in expansion

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#58]
consider using dotenv-expand but make it the default somehow

**Comment by jirka124** [comment]
Hey, is there in a meanwhile some workaround to it? Have tried using dotenv-expand on top of dotenvx but did not work, but wanna use dotenvx as its much more simpler to use with multi environment.

**Comment by motdotla** [comment]
there is a workaround if you use it in the traditional `require/import` way.

```
npm install @dotenvx/dotenvx --save
```

```
var dotenv = require('@dotenvx/dotenvx')
var dotenvExpand = require('dotenv-expand')

var myEnv = dotenv.config()
dotenvExpand.expand(myEnv)

console.log(process.env)
```

**Comment by motdotla** [comment]
https://github.com/dotenvx/dotenvx/pull/60

**Comment by jirka124** [comment]
Well, don't know what was I doing wrong, but can confirm that 0.15.0 works as expected so. Thank you very much, it's great module, keep it up.

**Comment by motdotla** [comment]
you weren't doing anything wrong - it just got added to `0.15.0`. it wasn't in `0.14.0`
