### ISSUE TITLE
more than `80` stars in such a short time. thank you everyone. 🙏

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#67]

**Comment by deadcoder0904** [comment]
that looks like a rad idea considering how many secret ops solutions haven't solved this problem easily.

congrats, this looks like a step in the right direction.

curious, which one to choose for a full-blown solution? dotenvx or dotenv-vault?

dotenv hub is a saas, right?

just confused with so many dotenv names lmao. my assumption is dotenvx with `.env.vault` commited to code & `.env.keys` commited to either private encrypted backup solution (self-hosted) or dotenv hub. am i wrong?

would definitely love guides on next.js, remix, docker (which i think exists)

**Comment by motdotla** [comment]
> that looks like a rad idea considering how many secret ops solutions haven't solved this problem easily.

right? thanks.

> dotenv hub is a saas

yes, but still in beta.

> my assumption is dotenvx with .env.vault commited to code & .env.keys commited to either private encrypted backup solution (self-hosted) or dotenv hub

exactly. hub will be extra convenient and integrate with your git flow, but we'll also provide guides and tooling to backup to 1password, s3, etc.

> which one to choose for a full-blown solution? dotenvx or dotenv-vault?

dotenv-vault is much more robust right now but has some dx annoyances dotenvx will solve. dotenv-vault was originally a sort of .env simpler clone of hashicorp vault with integrations to vercel, heroku, etc. then the .env.vault file was invented out of that effort. ever since then dotenv-vault has had some warts. it's flows were better suited to its original intention but i wanted to see the .env.vault file through. finally realized it really needed new tooling built around it. hence dotenvx.

**Comment by motdotla** [comment]
> would definitely love guides on next.js, remix, docker (which i think exists)

* remix: https://dotenvx.com/docs/package-managers/npm#remix
* next: https://dotenvx.com/docs/frameworks/next
* docker: https://dotenvx.com/docs/platforms/docker

**Comment by deadcoder0904** [comment]
@motdotla so only next.js guide isn't there. i thought remix too but i hadn't checked.

i'm curious to try it for my next.js project. what tools should i use?

is dotenvx (i have `.env.development` & `.env.production` in next.js right now) & dotenv.org (to backup secrets) enough? i am also making the project use docker with https://github.com/vercel/next.js/tree/canary/examples/with-docker-multi-env

woud love to know how you'll approach this?

ps: i think you should open discussions panel on github so we can discuss there.

**Comment by deadcoder0904** [comment]
so the saas isn't launched yet, right? i'm assuming it will be on dotenvx.com? should i use dotenv.org in the meantime?

**Comment by motdotla** [comment]
if it's just use right now i would:

1. use `dotenvx`
2. keep your `.env.keys` file backed up somewhere safe on your machine
3. configure your next ev script with `dotenvx run --env-file -- next dev` (or something along those lines)
4. generate your `.env.vault` with `dotenvx encrypt`
5. set your production `DOTENV_KEY` on vercel's environment variables (as far as i know this should still work with their docker deploys)

if you have a team you could share your `.env.keys` file over slack. it's a risk, but it's less of a risk than sharing your `.env` file. an attacker would have to get access to your slack (.env.keys) AND your code (.env.vault)

i would avoid dotenv.org unless really granular team control is important to you right now - like only junior devs get access to `.env` and only ops gets access to `.env.production`. dotenvx hub will get that but not for a few months.

**Comment by motdotla** [comment]
i'm literally turning you away from our fast growing revenue generating product right now 🤦‍♀️ haha. but as a dev myself, dotenvx just feels really ergonomic. i think you'll like it.

**Comment by deadcoder0904** [comment]
no problem. my first products are literally just me. hoping to launch more saas soon so i think we'll both be ready at the same time. you probably a lot before me.

**Comment by motdotla** [comment]
go get 'em 🫡
