### ISSUE TITLE
support `cross-env` convenience for windows users

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#68]
`cross-env` made it easy to set unix style environment variables and they work on windows. add similar type of support for dotenvx.

https://github.com/kentcdodds/cross-env/tree/afaae5518a03ac098fa773f7c613851b75d98b91

**Comment by motdotla** [comment]
more context: https://github.com/Hacker0x01/react-datepicker/pull/4174

**Comment by feledori** [comment]
Yes this would be really nice DX. This would allow us to only use this package for all our env needs. Thanks for your work!

**Comment by motdotla** [comment]
this is completed. the interface is slightly modified from cross-env.

cross-env example
```
cross-env NODE_ENV=production yourcommand
```

dotenvx example
```
dotenvx run --env="NODE_ENV=production" -- yourcommand
```

bit more verbose but this is because dotenvx does much more as well.
