### ISSUE TITLE
winget support (or scoop)

### ISSUE THREAD

**Issue by deadcoder0904** [dotenvx/dotenvx#69]
i use winget on windows (officially supported by microsoft) & scoop sometimes if winget isn't available.

**Comment by motdotla** [comment]
@deadcoder0904 what's your thoughts on chocolatey? we were thinking of starting there since it seems to have wider reach?

**Comment by deadcoder0904** [comment]
i never used chocolatey as i was on a mac for past 5-6 years, linux before that, & windows way before that.

i didn't even wanna use scoop but some packages aren't on winget.

you can go with just winget for the time being as its officially supported by microsoft.

i didn't know chocolatey had a huge ecosystem than both.

but yeah, windows installation methods shouldn't be ignored.

either that or just let people install `npm i -g dotenvx` like neon.tech did.

i couldn't use turso.tech because they didn't support windows installation without wsl. so went with better-sqlite3 instead.

**Comment by motdotla** [comment]
sounds good. for now you can use npx and npm global:

```
npm install @dotenvx/dotenvx -g
```
```
npx @dotenvx/dotenvx run --
```

there are also window exes available currently: https://dotenvx.com/docs/install#windows

**Comment by motdotla** [comment]
coming back to this. I think you're right that winget is where we should publish to.

but I looked into the process and it's still quite manual - open a PR on winget's repository (sort of like being part of homebrew core)

we will wait until dotenvx is much more feature complete. right now it has new releases almost daily.

until then, .exe downloads are updated and available here: https://dotenvx.com/docs/install#windows
