### ISSUE TITLE
reduce the total number of dependencies used

### ISSUE THREAD

**Issue by SuperchupuDev** [dotenvx/dotenvx#71]
as previously discussed, dotenvx currently uses a total of [219 dependencies](https://npmgraph.js.org/?q=@dotenvx/dotenvx) as of the time writing this issue (which includes 3 different versions of semver and get-stream, and other 17 duplicated dependencies). that's a really big number for a project like this, which significantly increases install times. optimizing the dependency count means less possible points of failure, less potentially vulnerable dependencies, and less energy consumption when fresh installing dependencies for _everyone_ using dotenvx

the current biggest direct dependencies this project uses are the following (some of them may install the same subdependency version making the total _slightly_ smaller):

- [update-notifier](https://npmgraph.js.org/?q=update-notifier%405.1.0) (83 (!!) dependencies)
- [@inquirer/prompts](https://npmgraph.js.org/?q=%40inquirer%2Fprompts%403.3.2) (41 dependencies)
- [winston](https://npmgraph.js.org/?q=winston%403.11.0) (30 dependencies)
- [ora](https://npmgraph.js.org/?q=ora%405.4.1) (29 dependencies)
- [conf](https://npmgraph.js.org/?q=conf%4010.2.0) (which is unused, see #70) (26 dependencies)
- [clipboardy](https://npmgraph.js.org/?q=clipboardy%402.3.0) (22 dependencies)

possible ways to achieve this:

- try to replicate some dependencies using pure node built-in behavior
- switch to different packages that can do the same but use less dependencies

i'm gonna try to contribute to reducing the dependency size as much as i can, but i'm opening this to bring awareness and encourage others to help

**Comment by motdotla** [comment]
`conf` is in use here https://github.com/dotenvx/dotenvx/blob/main/src/shared/store.js#L38

will consider reducing the others but all those are important at the moment.

i think the priority right now is feature building and then later we'll pair deps down. this project has a different ethos than `dotenv` (which was and always will be zero dependency). this project is largely distributed over binaries and is a swiss army knife of tooling for .env files.
