### ISSUE TITLE
bump update-notifier to fix vulnerability

### ISSUE THREAD

**Issue by MrHertal** [dotenvx/dotenvx#76]
Hi,

I'm using this package and `yarn audit` shows one moderate vulnerability due to one dependency:

```

yarn audit
yarn audit v1.22.21
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Got allows a redirect to a UNIX socket                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=11.8.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @dotenvx/dotenvx                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @dotenvx/dotenvx > update-notifier > latest-version >        │
│               │ package-json > got                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1088948                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
1 vulnerabilities found - Packages audited: 1094
Severity: 1 Moderate
```

This is because of `update-notifier@5.1.0` in the dependency, it should be upgraded.

I checked the commit history, and saw this commit from dependabot: https://github.com/dotenvx/dotenvx/commit/dc1454f7c8ee8f8b8a69c1c642f73b2d4c73ac29

But it has been erased some time later by this commit: https://github.com/dotenvx/dotenvx/commit/29dc7a04ac657250826e0330c539785ea12baccb

Could you upgrade `update-notifier` to clear that vulnerability?

Thanks

**Comment by motdotla** [comment]
we're caught between a rock and a hard place on this one currently. we're not using ESM and we've run into edge cases packaging esm modules up into our binary distributions.

so for now, we have to stay on the common js supported update-notifier 5.1.0. (sindre doesn't support common on any of his modules going forward). we are in the company of many others doing this as you can see from the downloads count here:

<img width="1291" alt="image" src="https://github.com/dotenvx/dotenvx/assets/3848/b55ed725-9779-4fbf-af3e-1aff01c2d170">


we're hopeful to switch all this when node's single executable matures: https://nodejs.org/api/single-executable-applications.html (or we are also considering using deno for packaging)
