### ISSUE TITLE
Unable to Decrypt in Vercel Development

### ISSUE THREAD

**Issue by zach-pp** [dotenvx/dotenvx#77]
My Vercel `develop` build is failing, executing `dotenvx run -- next build`. It succeeds for Preview and Production builds. 

```
> dotenvx run -- next build
--
12:17:10.835 |  
12:17:11.179 | [dotenvx@0.14.1] missing .env file (/vercel/path0/apps/web/.env)
12:17:11.179 | ? in development: use [dotenvx decrypt] to decrypt .env.vault to .env and then re-run [dotenvx run -- next build]
12:17:11.180 | ? for production: set [DOTENV_KEY] on your server and re-deploy
12:17:11.180 | ? for ci: set [DOTENV_KEY] on your ci and re-build
```

All three have `DOTENV_KEY` environment variables configured:

![image](https://github.com/dotenvx/dotenvx/assets/140201689/764543be-3512-4358-8bdd-aa331828aadf)

Feels like I'm missing something.

Thanks!

**Comment by motdotla** [comment]
hmm. that looks like it's not picking up the `DOTENV_KEY` for some reason.

if you run the command `echo $DOTENV_KEY` in front of `dotenvx run`, does it echo out the `DOTENV_KEY` set in Vercel?

something like this:

```
echo $DOTENV_KEY && dotenvx run -- next build
```

**Comment by motdotla** [comment]
if it's not there, can you try setting your `DOTENV_KEY` via the cli on every environment? that is what we documented here:

https://dotenvx.com/docs/platforms/vercel#set-dotenv-key

```
npx vercel@latest env add DOTENV_KEY
```

and then start walking that backward to see where it is being lost. Vercel has a multiple layers of environment variables so maybe there is some edge case there.

**Comment by motdotla** [comment]
you're right, it doesn't. i was thinking of the 'preview' branches.

this is very strange. maybe try setting your `DOTENV_KEY` in development to a sensitive key like the other two?

**Comment by motdotla** [comment]
sounds good, but yeah, seems Vercel related if it is fine in prod and staging and i've been unable to duplicate in development on my own Vercel so far.

in 6 months we will have many more guides and will have probably patched many more edge case bugs so maybe this edge case will surface during that time.

best of luck.

**Comment by motdotla** [comment]
hi @zach-pp, some changes since this thread:

1. `.env.vault` mechanism is being deprecated.
2. in its place are encrypted `.env` files using public-key encryption algorithm secp256k1
3. an updated Vercel guide is here and seemed to work well for me (i went through it a couple times with a real world project): https://dotenvx.com/docs/platforms/vercel
