### ISSUE TITLE
dotenvx fails when running with Docker Build

### ISSUE THREAD

**Issue by lousando** [dotenvx/dotenvx#78]
I'm testing that I can pass in keys as built secret to decrypt the vault inside this docker image.

Command Run:

`dotenvx run -f .env.keys -- docker build --secret type=env,id=DOTENV_KEY . -t web`

Output:

```
[dotenvx@0.15.4] injecting env (3) from .env.keys
[+] Building 0.0s (0/0)                                                                                                                               docker:desktop-linux
ERROR: failed to stat DOTENV_KEY: stat DOTENV_KEY: no such file or directory
Command failed with exit code 1: docker build --secret type=env,id=DOTENV_KEY . -t trolley
command [docker build --secret type=env,id=DOTENV_KEY . -t trolley] failed

  try without dotenvx: [docker build --secret type=env,id=DOTENV_KEY . -t web]

if that succeeds, then dotenvx is the culprit. report issue:
<https://github.com/dotenvx/dotenvx/issues/new>
```

Environment:

- dotenv 0.15.4
- Apple M2 Pro (14.2.1)
- Running inside of Fish shell, but I've also tested with `bash` and `zsh` with the same error.

**Comment by motdotla** [comment]
hi @lousando, you can't actually pass in `.env.keys` files. they are really a non-committed collection file to collect all your keys in a convenient spot. to use with docker you can follow this guide:

https://dotenvx.com/docs/platforms/docker

or in your case if you want to wrap the docker build command like that you can do this:

```
DOTENV_KEY='<put your DOTENV_KEY_PRODUCTION here>' dotenvx run -- docker build --secret type=env,id=DOTENV_KEY . -t web
```

**Comment by motdotla** [comment]
yeah, if you are passing directly to echo you need to execute another process. for example:

```
$ echo "HELLO=World" > .env
$ dotenvx run --quiet -- sh -c 'echo $HELLO'
```

**Comment by lousando** [comment]
Ah, I see, thank you! 🙏 
Great work on this btw!

**Comment by motdotla** [comment]
for docker we do recommend you include the `.env.vault` in the built container image though. then you can just pass a single `DOTENV_KEY` to it on run.

https://dotenvx.com/docs/platforms/docker#set-dotenv-key

```
docker build -t app . && docker run -e "DOTENV_KEY=dotenv://:key_10283719af6a30ef49050048617f4fea10c23a38021fbebeb9fd858caa01852e@dotenvx.com/vault/.env.vault?environment=production" -it --init --rm -p 3000:3000 app
```

this simplifies, making changes going forward. you never have to change your run command. just re-encrypt your .env.vault file, build the docker image, and ship it.
