### ISSUE TITLE
dotenvx fails to run ES Module node app if installed via brew but works via npm

### ISSUE THREAD

**Issue by andrewjli** [dotenvx/dotenvx#86]
I tried running a TypeScript node app with dotenvx installed via `brew`, and it resulted in a CommonJS import error. But interestingly, this error does not occur when running the same app with dotenvx installed via `npm i -g @dotenvx/dotenvx` (and it doesn't occur when not using dotenvx too).

Let me know if here's any further details I can provide.

```
andrewli@mac test % dotenvx run -- node dist/index
[dotenvx@0.16.1] injecting env (4) from .env
node:internal/modules/cjs/loader:1156
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/andrewli/Projects/test/dist/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12) {
  code: 'ERR_REQUIRE_ESM'
}
Command failed with exit code 1: node dist/index
command [node dist/index] failed

  try without dotenvx: [node dist/index]

if that succeeds, then dotenvx is the culprit. report issue:
<https://github.com/dotenvx/dotenvx/issues/new>
```

**Comment by motdotla** [comment]
investigating. sorry about this.

**Comment by motdotla** [comment]
does this error still occur if you upgrade to `v0.17.1`? `brew reinstall dotenvx/brew/dotenvx`

1. i've added a very basic typescript example on the README. it succeeds:

<img width="884" alt="Screenshot 2024-02-21 at 9 05 29 AM" src="https://github.com/dotenvx/dotenvx/assets/3848/b0b2e41d-5feb-4a23-9d3b-f763870a70d8">

2. can you share more about what your `dist/index.js` file looks like? maybe a paired down version.
3. what version of node are you running?

**Comment by andrewjli** [comment]
Apologies for the delay. 

I think what's obvious is that the issue stems from the fact that the app is an ES Module and has no CommonJS exports, which is not the case for your TypeScript example.

The reason I chose this approach was because a [library](https://github.com/sindresorhus/got) I wanted to try is pure ESM. I started developing on a Windows machine, and didn't notice any issues because there is no `brew` on Windows, so I installed it globally via `npm`. But when I shifted to my Macbook to continue, I installed `dotenvx` via `brew` and encountered this issue.

In any case, here is a minimal repro of the issue:
https://github.com/andrewjli/dotenvx-repro

These are the versions I'm used to reproduce the issue.

```
andrewli@mac dotenvx-repro % dotenvx --version
0.19.1

andrewli@mac dotenvx-repro % node -v
v21.6.2
```

Here is the console output of trying to run with `dotenvx`

```
andrewli@mac dotenvx-repro % brew reinstall dotenvx/brew/dotenvx
==> Fetching dotenvx/brew/dotenvx
==> Downloading https://github.com/dotenvx/dotenvx/releases/download/v0.19.1/dotenvx-0.19.1-darwin-amd64.tar.gz
==> Reinstalling dotenvx/brew/dotenvx 
Warning: Your Xcode (15.0.1) is outdated.
Please update to Xcode 15.1 (or delete it).
Xcode can be updated from the App Store.

🍺  /usr/local/Cellar/dotenvx/64: 4 files, 58MB, built in 12 seconds
==> Running `brew cleanup dotenvx`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

andrewli@mac dotenvx-repro % dotenvx --debug run -- node dist/index.js
process command [node dist/index.js]
options: {"envFile":".env","envVaultFile":".env.vault"}
loading env from /Users/andrewli/Projects/dotenvx-repro/.env
{"NAME":"Bob"}
NAME set
NAME set to Bob
[dotenvx@0.19.1] injecting env (1) from .env
executing process command [node dist/index.js]
node:internal/modules/cjs/loader:1156
      throw err;
      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/andrewli/Projects/dotenvx-repro/dist/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12) {
  code: 'ERR_REQUIRE_ESM'
}
Command failed with exit code 1: node dist/index.js
command [node dist/index.js] failed

  try without dotenvx: [node dist/index.js]

if that succeeds, then dotenvx is the culprit. report issue:
<https://github.com/dotenvx/dotenvx/issues/new>

andrewli@mac dotenvx-repro % node dist/index.js
Hello, undefined

andrewli@mac dotenvx-repro % brew uninstall dotenvx
Uninstalling /usr/local/Cellar/dotenvx/64... (4 files, 58MB)

andrewli@mac dotenvx-repro % npm -g i @dotenvx/dotenvx

added 259 packages in 25s

53 packages are looking for funding
  run `npm fund` for details

andrewli@mac dotenvx-repro % dotenvx --debug run -- node dist/index.js
process command [node dist/index.js]
options: {"envFile":".env","envVaultFile":".env.vault"}
loading env from /Users/andrewli/Projects/dotenvx-repro/.env
{"NAME":"Bob"}
NAME set
NAME set to Bob
[dotenvx@0.19.1] injecting env (1) from .env
executing process command [node dist/index.js]
Hello, Bob
```

Please let me know if there's any other information I can provide.

**Comment by motdotla** [comment]
thanks @andrewjli, this is really helpful. this is my main priority this weekend if not sooner.

**Comment by motdotla** [comment]
@andrewjli i was able to duplicate this issue and have the patch. install dotenvx `0.20.1` or greater. see if it works for you. working for me now.

https://github.com/dotenvx/dotenvx/assets/3848/79194c2c-c178-40ae-b24c-24f1d5ce6e4a

**Comment by andrewjli** [comment]
@motdotla Can confirm it now works fine when installed from brew! Thanks!
