### ISSUE TITLE
test in windows

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#99]
i need to do some heavy usage testing in windows. i haven't done that yet and have been relying on the community to report any issues.

**Comment by ali-layken** [comment]
![image](https://github.com/dotenvx/dotenvx/assets/10457831/bc1be70a-eba3-435c-a055-4b8a4c14296a)

which is not found and my main.ts works

**Comment by motdotla** [comment]
@ali-layken if you downgrade to `v0.20.0` does it function correctly? I think this bug for windows might have been introduced in `v0.20.1`

**Comment by ali-layken** [comment]
> @ali-layken if you downgrade to `v0.20.0` does it function correctly? I think this bug for windows might have been introduced in `v0.20.1`

I am not sure. Another worker on my team included it in another project at 0.15.4 and said it worked on windows fine so I reverted to 0.15.4 and it worked fine so I didn't try any other version

**Comment by ntodorov** [comment]
@motdotla I had the same issue 12 hours ago. But today I tried again and I can see that npx installed @dotenvx/dotenvx@0.21.0 and it worked!

**Comment by GabrielBB** [comment]
We started seeing this error with `"@dotenvx/dotenvx": "^0.20.2"` . Downgrading to `"@dotenvx/dotenvx": "^0.19.1"` solves the problem. @motdotla I think you should be using a matrix with 3 operating systems here: https://github.com/dotenvx/dotenvx/blob/b4536fa2703020f7973a0d60d61a647202e6cb89/.github/workflows/ci.yml#L8 . Should I help with a PR ?

**Comment by motdotla** [comment]
@GabrielBB i think you're right. but i also think `0.21.0` or greater should work for you on windows. we're at `0.23.0` as of this writing.

**Comment by motdotla** [comment]
effort started here: https://github.com/dotenvx/dotenvx/pull/115

**Comment by motdotla** [comment]
we added a postrelease test here on windows. looking good and others are experiencing dotenvx.exe working well on windows: https://github.com/dotenvx/dotenvx/pull/141
